#pragma once
/**********************************************************************/
#define COMMS_ERROR_NONE 0
#define COMMS_ERROR_BADNETIDX 1
#define COMMS_ERROR_BADLOCIDX 2
#define COMMS_ERROR_BADDBLINK 3
#define COMMS_ERROR_NODATA 4
#define COMMS_ERROR_NOCOMMS 5
#define COMMS_ERROR_CREATEFILE 6
#define COMMS_ERROR_PRICESETRANGE 7
#define COMMS_ERROR_NOKEYBOARD 8
#define COMMS_ERROR_NOKBDMAN 9
#define COMMS_ERROR_BADKBDMAN 10
#define COMMS_ERROR_NETWORKLOCK 11
#define COMMS_ERROR_UPLOAD_TIMER 12
#define COMMS_ERROR_FTP_CONNECT 13
#define COMMS_ERROR_FTP_FOLDER_DIR 14
#define COMMS_ERROR_FTP_FOLDER_CHANGE 15
#define COMMS_ERROR_FTP_FOLDER_DEST 16
#define COMMS_ERROR_FTP_FILE_PUT 17
#define COMMS_ERROR_FTP_FILE_GET 18
#define COMMS_ERROR_FTP_FILE_RENAME 19
#define COMMS_ERROR_FTP_FILE_DELETE 20
#define COMMS_ERROR_FTP_FILE_TIMEOUT 21
#define COMMS_ERROR_FTP_FILE_AUTOQUIT 22
#define COMMS_ERROR_FTP_FILE_FAIL 23
/**********************************************************************/
