#pragma once
/**********************************************************************/

//stock level types
#define FILTERTYPE_DATABASE 0 
#define FILTERTYPE_DELIVERY 1
//removed filtertype_adjustment
#define FILTERTYPE_OPENING 3
#define FILTERTYPE_REORDER 4
#define FILTERTYPE_STOCKCODES 5
#define FILTERTYPE_TRANSFERS 6
#define FILTERTYPE_BROWSE_STOCK 7
#define FILTERTYPE_ORDERBROWSE_PREVIEW 8
#define FILTERTYPE_ORDERBROWSE_NEWITEM 9
#define FILTERTYPE_ORDERBROWSE_NEWORDER 10
#define FILTERTYPE_BROWSE_PLU 11
#define FILTERTYPE_BROWSE_OPENING 12
#define FILTERTYPE_BROWSE_STOCKTAKE 13
#define FILTERTYPE_BROWSE_TRANSFER 14
#define FILTERTYPE_STOCK_DELETION 15
#define FILTERTYPE_STOCKTAKE 16
#define FILTERTYPE_PLU_DELETION 17
#define FILTERTYPE_STOCK_ITEMSET 18

#define STOCK_FILTER_DESCRIPTION 1
#define STOCK_FILTER_STOCKCODE 2
#define STOCK_FILTER_SUPPREF 4

#define FIRST_CATEGORYSET_FILTER 10000
#define FIRST_DEPARTMENTSET_FILTER 10000
#define FIRST_SUPPLIERSET_FILTER 10000

/**********************************************************************/

