#pragma once
/**********************************************************************/
#define MAX_LENGTH_UNIT_NAME 25
#define MAX_LENGTH_STOCK_DESCRIPTION 32
#define MAX_LENGTH_ADDRESS_NAME 25
#define MAX_LENGTH_ADDRESS_STREET 35
#define MAX_LENGTH_ADDRESS_POSTCODE 10
#define MAX_LENGTH_ADDRESS_PHONE 20
#define MAX_LENGTH_ADDRESS_EMAIL 50
#define MAX_LENGTH_ADDRESS_FAX 25
#define MAX_LENGTH_ADDRESS_ACCOUNT 50
#define MAX_LENGTH_TAXNO 15
#define MAX_LENGTH_PRICELEVEL_TEXT 15
#define MAX_LENGTH_MODIFIER 20
#define MAX_LENGTH_IDRAUGHT_ID 20
#define MAX_LENGTH_REMOTE_ID 16

#define MAX_LENGTH_GENERAL_NAME 30
#define MAX_LENGTH_GENERAL_REFERENCE 30
#define MAX_LENGTH_GENERAL_REASON 50

#define MAX_LENGTH_CURRENCY_SYMBOL 3
#define MAX_LENGTH_INSTRUCTIONS 100
#define MAX_LENGTH_SEARCH_TEXT 40
#define MAX_LENGTH_NETWORK_CODE 9
#define MAX_LENGTH_ADHOC_PREFIX 10
#define MAX_LENGTH_DEPTNO 3

#define MAX_LENGTH_NETWORK_PHONE 32
#define MAX_LENGTH_NETWORK_SERVER 50
#define MAX_LENGTH_NETWORK_REMPATH 80
#define MAX_LENGTH_NETWORK_USERNAME 50
#define MAX_LENGTH_NETWORK_PASSWORD 50

#define MAX_LENGTH_FTP_USERNAME 50
#define MAX_LENGTH_FTP_PASSWORD 50

#define MAX_LENGTH_SPTBOOK_SITE 50
#define MAX_LENGTH_SPTBOOK_USERNAME 50
#define MAX_LENGTH_SPTBOOK_PASSWORD 50

#define MAX_LENGTH_IDRAUGHT_SERVER 50
#define MAX_LENGTH_IDRAUGHT_USERNAME 50
#define MAX_LENGTH_IDRAUGHT_PASSWORD 50

#define MAX_LENGTH_FTP_SERVER 50
#define MAX_LENGTH_FTP_USERNAME 50
#define MAX_LENGTH_FTP_PASSWORD 50
#define MAX_LENGTH_FTP_FOLDER 50
#define MAX_LENGTH_CHARTWELLS_PASSWORD 500
#define MAX_LENGTH_CHARTWELLS_SITENO 20

#define MAX_LENGTH_ADDRESS_MULTI_EMAIL 1000

#define MAX_LENGTH_SMTP_SERVER 50
#define MAX_LENGTH_SMTP_USERNAME 50
#define MAX_LENGTH_SMTP_PASSWORD 50
#define MAX_LENGTH_SMTP_ADDRESS 50

#define MAX_LENGTH_BILL_TEXT 40
#define MAX_LENGTH_RECEIPT_TEXT 40

#define MAX_LENGTH_EMAIL_SIGNATURE 2000

#define MAX_LENGTH_LOCATION_NOTES 5000

#define MAX_LENGTH_TERMINAL_NAME 20

#define MAX_LENGTH_OPGROUP_NAME 20

#define MAX_LENGTH_OPNAME 20

#define MAX_LENGTH_AGRESSO_LOCGROUP 2
/**********************************************************************/
