#pragma once
/**********************************************************************/
#define POSUTILITY_STATUS_NOT_CHECKED 0
#define POSUTILITY_STATUS_CHECKING 1
#define POSUTILITY_STATUS_NO_SYSTEM 2
#define POSUTILITY_STATUS_GOT_SYSTEM 3
#define POSUTILITY_STATUS_UPDATING 4
#define POSUTILITY_STATUS_NOT_REGISTERED 5
#define POSUTILITY_STATUS_WAIT_INITSYSTEM 6
#define POSUTILITY_STATUS_WAIT_TASK 7
#define POSUTILITY_STATUS_WAIT_FNB 8
#define POSUTILITY_STATUS_WAIT_S4LABOUR 9
#define POSUTILITY_STATUS_WAIT_LIPA 10
#define POSUTILITY_STATUS_WAIT_CHARTWELLS 11
#define POSUTILITY_STATUS_WAIT_BACKUP 12
/**********************************************************************/