#pragma once
/**********************************************************************/
#define CONVERT_ERROR_NONE 200
#define CONVERT_ERROR_PARAMS 201
#define CONVERT_ERROR_SOURCE_NOT_FOUND 202
#define CONVERT_ERROR_SOURCE_NO_DATA 203
#define CONVERT_ERROR_DEST_NOT_FOUND 204
#define CONVERT_ERROR_FAIL_COPY 205
#define CONVERT_ERROR_USER_CANCEL 206
#define CONVERT_ERROR_TEMPFOLDER_CREATE 207
#define CONVERT_ERROR_TEMPFOLDER_DELETE 208
#define CONVERT_ERROR_TEMPFOLDER_RENAME 209
#define CONVERT_ERROR_PROGFOLDER_RENAME 210
#define CONVERT_ERROR_ALREADY_RUNNING 211
#define CONVERT_ERROR_INVALID_DATA 212
#define CONVERT_ERROR_DATAPATH_OPEN 213
#define CONVERT_ERROR_DATAPATH_NOT_FOUND 214
#define CONVERT_ERROR_NONE_NOREBUILD 300
/**********************************************************************/
