#pragma once
/******************************************************************************/
#define SMARTPAYFIELD_USERID 0
#define SMARTPAYFIELD_USERNAME 1
#define SMARTPAYFIELD_FORENAME 2
#define SMARTPAYFIELD_SURNAME 3
#define SMARTPAYFIELD_DOB 4
#define SMARTPAYFIELD_EXPIRYDATE 5
#define SMARTPAYFIELD_GENDER 6
#define SMARTPAYFIELD_GROUPNO 7
#define SMARTPAYFIELD_DAYGROUPS 8
#define SMARTPAYFIELD_EMAIL 9
#define SMARTPAYFIELD_INFO1 10
#define SMARTPAYFIELD_INFO2 11
#define SMARTPAYFIELD_INFO3 12
#define SMARTPAYFIELD_INFO4 13
#define SMARTPAYFIELD_INFO5 14
#define SMARTPAYFIELD_INFO6 15
#define SMARTPAYFIELD_INFO7 16
#define SMARTPAYFIELD_INFO8 17
#define SMARTPAYFIELD_TICK1 18
#define SMARTPAYFIELD_TICK2 19
#define SMARTPAYFIELD_TICK3 20
#define SMARTPAYFIELD_TICK4 21
#define SMARTPAYFIELD_ALLERGYCODES 22
#define SMARTPAYFIELD_DIETARY 23
#define SMARTPAYFIELD_INACTIVE 24
/*****/
#define SMARTPAYFIELD_MEMBERID 25
#define SMARTPAYFIELD_EXTERNALREF1 26
#define SMARTPAYFIELD_EXTERNALREF2 27
#define SMARTPAYFIELD_PREVIOUS_USERID 28
#define SMARTPAYFIELD_NEXT_USERID 29
/*****/
#define SMARTPAYFIELD_PURSE1_ALLOW 30
#define SMARTPAYFIELD_PURSE1_LIABILITY 31
#define SMARTPAYFIELD_PURSE1_CREDIT 32
#define SMARTPAYFIELD_PURSE1_LASTSPENDDATE 33
#define SMARTPAYFIELD_PURSE1_LASTSPENDTIME 34
#define SMARTPAYFIELD_PURSE1_LASTSPEND 35
#define SMARTPAYFIELD_PURSE1_SPENDTODATE 36
/*****/
#define SMARTPAYFIELD_PURSE2_ALLOW 37
#define SMARTPAYFIELD_PURSE2_BALANCE 38
#define SMARTPAYFIELD_PURSE2_LASTSPENDDATE 39
#define SMARTPAYFIELD_PURSE2_LASTSPENDTIME 40
#define SMARTPAYFIELD_PURSE2_LASTSPEND 41
#define SMARTPAYFIELD_PURSE2_SPENDTODATE 42
#define SMARTPAYFIELD_PURSE2_REFRESHFLAGS 43
#define SMARTPAYFIELD_PURSE2_REFRESHED_DATE 44
#define SMARTPAYFIELD_PURSE2_REFRESHED_TIME 45
/*****/
#define SMARTPAYFIELD_PURSE3_ALLOW 46
#define SMARTPAYFIELD_PURSE3_LIABILITY 47
#define SMARTPAYFIELD_PURSE3_CREDIT 48
#define SMARTPAYFIELD_PURSE3_LASTSPENDDATE 49
#define SMARTPAYFIELD_PURSE3_LASTSPENDTIME 50
#define SMARTPAYFIELD_PURSE3_LASTSPEND 51
#define SMARTPAYFIELD_PURSE3_SPENDTODATE 52
/*****/
#define SMARTPAYFIELD_CASH_SPENDTODATE 53
/*****/
#define SMARTPAYFIELD_POINTS 54
#define SMARTPAYFIELD_POINTS_TODATE 55
/*****/
#define SMARTPAYFIELD_OWNMAXSPEND 56
/*****/
#define SMARTPAYFIELD_MAXSPEND_PURSE1_PERIOD1 57
#define SMARTPAYFIELD_MAXSPEND_PURSE1_PERIOD2 58
#define SMARTPAYFIELD_MAXSPEND_PURSE1_PERIOD3 59
#define SMARTPAYFIELD_MAXSPEND_PURSE1_PERIOD4 60
#define SMARTPAYFIELD_MAXSPEND_PURSE1_PERIOD5 61
#define SMARTPAYFIELD_MAXSPEND_PURSE1_PERIOD6 62
/*****/
#define SMARTPAYFIELD_MAXSPEND_PURSE3_PERIOD1 63
#define SMARTPAYFIELD_MAXSPEND_PURSE3_PERIOD2 64
#define SMARTPAYFIELD_MAXSPEND_PURSE3_PERIOD3 65
#define SMARTPAYFIELD_MAXSPEND_PURSE3_PERIOD4 66
#define SMARTPAYFIELD_MAXSPEND_PURSE3_PERIOD5 67
#define SMARTPAYFIELD_MAXSPEND_PURSE3_PERIOD6 68
/*****/
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE1_PERIOD1 69
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE1_PERIOD2 70
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE1_PERIOD3 71
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE1_PERIOD4 72
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE1_PERIOD5 73
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE1_PERIOD6 74
/*****/
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE3_PERIOD1 75
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE3_PERIOD2 76
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE3_PERIOD3 77
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE3_PERIOD4 78
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE3_PERIOD5 79
#define SMARTPAYFIELD_MAXOVERDRAFT_PURSE3_PERIOD6 80
/*****/
#define SMARTPAYFIELD_ALERTCODE 81
#define SMARTPAYFIELD_ALERTDATE 82
#define SMARTPAYFIELD_ALERTTIME 83
/*****/
#define SMARTPAYFIELD_FULLUSERID 84
#define SMARTPAYFIELD_FORENAME_SURNAME 85
#define SMARTPAYFIELD_GROUP_TYPE 86
#define SMARTPAYFIELD_GROUP_USERID 87
#define SMARTPAYFIELD_GROUP_TYPE_USERID 88
#define SMARTPAYFIELD_GROUP_FULLUSERID 89
#define SMARTPAYFIELD_GROUP_TYPE_FULLUSERID 90
#define SMARTPAYFIELD_TEXT 91
/*****/
#define SMARTPAYFIELD_GROUPSHIFT_STATUS 92
#define SMARTPAYFIELD_GROUPSHIFT_STARTDATE 93
#define SMARTPAYFIELD_GROUPSHIFT_ENDDATE 94
#define SMARTPAYFIELD_GROUPSHIFT_FUTUREGROUP 95

/******************************************************************************/

class CSmartPayHeaderHelpers
{
public:
	CSmartPayHeaderHelpers();
	
public:
	CString GetHeaderFull() { return m_strHeaderFull; }
	CString GetHeaderBiometric() { return m_strHeaderBiometric; }

public:
	void SetHeaderFull(CString str) { m_strHeaderFull = str;  }
	void SetHeaderBiometric(CString str) { m_strHeaderBiometric = str; }

public:
	void UpdateLegacyField(CString& strField);
	void CreateNumericHeader(CString strHeader, CArray<int, int>& arrayHeader);
	void CreateNumericHeader(CCSV& csvHeader, CArray<int, int>& arrayHeader);
	int GetNumericField(CString strField);

private:
	void AddFieldToHeader(CString strHeader, bool bAllowWithBiometric = TRUE);
	void AddFieldToHeaderMap(CString strField, int nFieldNo);

private:
	CMap <CString, LPCTSTR, int, int> m_HeaderMap;

private:
	CString m_strHeaderFull;
	CString m_strHeaderBiometric;
};

/******************************************************************************/
extern CSmartPayHeaderHelpers SmartPayHeaderHelpers;
/******************************************************************************/
