//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartPay4Manager.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_PROGRESS                 101
#define IDD_ACCOUNTLINK_PARENTPAY       102
#define IDD_ACCOUNTLINK_PEBBLE          103
#define IDD_ACCOUNTLINK_WISEPAY         104
#define IDD_ADDCASH                     105
#define IDD_ADDPOINTS                   106
#define IDD_ALERTTEXT                   107
#define IDD_ALLERGIES                   108
#define IDD_ATCARCHIVE                  109
#define IDD_BACKGROUNDTIMETABLE         110
#define IDD_BACKUP_INFO                 111
#define IDD_BACKUP_PROGRESS             112
#define IDD_BACKUP_PROMPT               113
#define IDD_BACKUP_RESULT               114
#define IDD_BACKUP_TYPE                 115
#define IDD_BIRTHDAYS                   116
#define IDD_CARDARCHIVE                 117
#define IDD_CARDNO                      118
#define IDD_CARDPICKER                  119
#define IDD_COLOUR_EDIT                 120
#define IDD_COLUMN_LIST                 121
#define IDD_COMMENT                     122
#define IDD_CREDIT_ADJUST               123
#define IDD_DATABASEIMPORT              124
#define IDD_DATABASE_REPORTS            125
#define IDD_DEF_EDIT                    126
#define IDD_DEF_EDIT_EMAIL              127
#define IDD_DELETELEAVER                128
#define IDD_EDITCUSTOMLIST              129
#define IDD_EDIT_STAMPS                 130
#define IDD_ENDOFDAY                    131
#define IDD_ENDOFDAY_REGEN              132
#define IDD_EPOS_TERMINALS              133
#define IDD_FIND                        134
#define IDD_GROUPNO                     135
#define IDD_GROUPPICKER                 136
#define IDD_GROUPSHIFT                  137
#define IDD_HEADER_WARN                 138
#define IDD_HOTLIST                     139
#define IDD_HOTLISTTRACE                140
#define IDD_IMPORTRECORDS               141
#define IDD_IMPORTSIMS                  142
#define IDD_IMPORTSTATS                 143
#define IDD_IMPORTWONDE                 144
#define IDD_LIST_DATA                   145
#define IDD_LIST_DATA_DELETE            146
#define IDD_MESSAGE                     147
#define IDD_MOVELEAVERS                 148
#define IDD_OFFICEMEAL                  149
#define IDD_PASSWORD                    150
#define IDD_PASSWORD_LIST               151
#define IDD_PASSWORD_LOG                152
#define IDD_PERIODREFRESHLIST           153
#define IDD_PHOTOID                     154
#define IDD_PHOTOIDLIST                 155
#define IDD_PURCHASECONTROLSTAMP_DELETE 156
#define IDD_PURCHASECONTROLSTAMP_MODIFY 157
#define IDD_REDEEMPOINTS                158
#define IDD_REFRESHDAYS                 159
#define IDD_REFRESHMONTH                160
#define IDD_REFRESHWEEKLY               161
#define IDD_REFRESHYEAR                 162
#define IDD_REPORT_AUDIT                163
#define IDD_REPORT_AUDIT_ACTION         164
#define IDD_REPORT_GROUPSHIFT           165
#define IDD_REPORT_KIOSKAUDIT           166
#define IDD_REPORT_PAYMENTAUDIT         167
#define IDD_REPORT_PCAUDIT              168
#define IDD_REPORT_PEBBLELINK           169
#define IDD_REPORT_PERIOD               170
#define IDD_REPORT_PURCHASECONTROL      171
#define IDD_REPORT_STARTINGBALANCE      172
#define IDD_REPORT_WEEKLYSPEND          173
#define IDD_SELECT_IMPORT_TYPE          174
#define IDD_SELECT_MULTIPLE_ENTITY      175
#define IDD_SERVICE_INSTALL             176
#define IDD_SERVICE_LOGON               177
#define IDD_SETDAYGROUPS                178
#define IDD_SETUP_BGNDOPTIONS           179
#define IDD_SETUP_BROMCOM               180
#define IDD_SETUP_EODTEXTS              181
#define IDD_SETUP_EPOSPATHS             182
#define IDD_SETUP_EXPORTSALES           183
#define IDD_SETUP_FIELDS                184
#define IDD_SETUP_GROUPPERIOD2          185
#define IDD_SETUP_PARENTMAIL            186
#define IDD_SETUP_PARENTPAY             187
#define IDD_SETUP_PARENTPAY2            188
#define IDD_SETUP_PASSWORDOPTIONS       189
#define IDD_SETUP_PEBBLE                190
#define IDD_SETUP_PEBBLE_PAYMENT        191
#define IDD_SETUP_PEBBLE_SPOSPAYTYPE    192
#define IDD_SETUP_PERIODS               193
#define IDD_SETUP_PHOTOID               194
#define IDD_SETUP_READER                195
#define IDD_SETUP_SCHOOLCOMMS           196
#define IDD_SETUP_SIMS                  197
#define IDD_SETUP_SQUID                 198
#define IDD_SETUP_TUCASI                199
#define IDD_SETUP_TUCASIV2              200
#define IDD_SETUP_USERTEXTS             201
#define IDD_SETUP_WEBPAYMENTOPTIONS     202
#define IDD_SETUP_WISEPAY               203
#define IDD_SETUP_WISEPAY2              204
#define IDD_SETUP_WONDE                 205
#define IDD_SIMULATE_READER             206
#define IDD_SMARTPAYMANAGER_DIALOG      207
#define IDD_SMTP_ERROR                  208
#define IDD_SMTP_RESULTS                209
#define IDD_SQLDB_TWEAK                 210
#define IDD_SURNAMELIST                 211
#define IDD_TERMINALSETS                212
#define IDD_TOO_MANY_USERS              213
#define IDD_UPGRADE                     214
#define IDD_WAIT                        215
#define IDD_WAIT_LOCK                   216
#define IDD_WEBPAYMENTIMPORTLOG         217
#define IDD_WEBPAYMENTLINKSQUID         218
#define IDD_WEBPAYMENTRESEND            219
#define IDD_WEBPAYMENTSTATS             220
#define IDD_WORKING                     221
#define IDR_MAINFRAME                   222
#define IDR_MENU1                       223
#define IDR_MENU2                       224
#define IDR_MENU3                       225
#define IDR_MENU4                       226
#define IDR_MENU5                       227
#define IDD_PROPPAGE_ACCUMULATOR1       1000
#define IDD_PROPPAGE_BACKUP_MODE        1001
#define IDD_PROPPAGE_BACKUP_SCHEDULE    1002
#define IDD_PROPPAGE_BATCH1             1003
#define IDD_PROPPAGE_BATCH2             1004
#define IDD_PROPPAGE_BATCH3             1005
#define IDD_PROPPAGE_BATCH5             1006
#define IDD_PROPPAGE_CSVIMPORT1         1007
#define IDD_PROPPAGE_CSVIMPORT2         1008
#define IDD_PROPPAGE_CSVIMPORT3         1009
#define IDD_PROPPAGE_CSVIMPORT4         1010
#define IDD_PROPPAGE_EDITRECORD_BALANCE 1011
#define IDD_PROPPAGE_EDITRECORD_DETAIL  1012
#define IDD_PROPPAGE_EDITRECORD_EXTERNAL 1013
#define IDD_PROPPAGE_EDITRECORD_MAXSPEND 1014
#define IDD_PROPPAGE_EDITRECORD_PURCHASECONTROL 1015
#define IDD_PROPPAGE_EMAILALERT1        1016
#define IDD_PROPPAGE_EMAILALERT2        1017
#define IDD_PROPPAGE_EMAILALERT3        1018
#define IDD_PROPPAGE_EMAILALERT4        1019
#define IDD_PROPPAGE_EXPORT1            1020
#define IDD_PROPPAGE_EXPORT2            1021
#define IDD_PROPPAGE_EXPORT3            1022
#define IDD_PROPPAGE_EXPORT4            1023
#define IDD_PROPPAGE_GROUP1             1024
#define IDD_PROPPAGE_GROUP2             1025
#define IDD_PROPPAGE_GROUP6             1026
#define IDD_PROPPAGE_GROUP7             1027
#define IDD_PROPPAGE_GROUP8             1028
#define IDD_PROPPAGE_PURCHASE1          1029
#define IDD_PROPPAGE_PURCHASE2          1030
#define IDD_PROPPAGE_REPORTPLU          1031
#define IDD_PROPPAGE_SERVER1            1032
#define IDD_PROPPAGE_SERVER2            1033
#define IDD_PROPPAGE_SERVER3            1034
#define IDD_PROPPAGE_SERVER5            1035
#define IDD_PROPPAGE_SERVER6            1036
#define IDD_PROPPAGE_SYSTEM1            1037
#define IDD_PROPPAGE_SYSTEM10           1038
#define IDD_PROPPAGE_SYSTEM2            1039
#define IDD_PROPPAGE_SYSTEM3            1040
#define IDD_PROPPAGE_SYSTEM5            1041
#define IDD_PROPPAGE_SYSTEM6            1042
#define IDD_PROPPAGE_SYSTEM7            1043
#define IDD_PROPPAGE_SYSTEM8            1044
#define IDD_PROPPAGE_SYSTEM9            1045
#define IDD_PROPPAGE_XFER1              1046
#define IDD_PROPPAGE_XFER2              1047
#define IDD_PINADMIN                    1048
#define IDD_PINRANGE                    1049
#define IDC_BUTTON1                     1500
#define IDC_BUTTON2                     1501
#define IDC_BUTTON3                     1502
#define IDC_BUTTON4                     1503
#define IDC_BUTTON5                     1504
#define IDC_BUTTON6                     1505
#define IDC_BUTTON_5DAYS                1506
#define IDC_BUTTON_7DAYS                1507
#define IDC_BUTTON_ACCEPT               1508
#define IDC_BUTTON_ACTION               1509
#define IDC_BUTTON_ACTION1              1510
#define IDC_BUTTON_ACTION2              1511
#define IDC_BUTTON_ACTION3              1512
#define IDC_BUTTON_ACTION4              1513
#define IDC_BUTTON_ADD                  1514
#define IDC_BUTTON_ALERT                1515
#define IDC_BUTTON_REMOVE               1515
#define IDC_BUTTON_ALL                  1516
#define IDC_BUTTON_ALLERGIES            1517
#define IDC_BUTTON_ALTKEY1              1518
#define IDC_BUTTON_ALTKEY2              1519
#define IDC_BUTTON_ALTKEY3              1520
#define IDC_BUTTON_BACKGROUND           1521
#define IDC_BUTTON_BALANCES             1522
#define IDC_BUTTON_BROWSE               1523
#define IDC_BUTTON_BROWSE2              1524
#define IDC_BUTTON_BROWSE_LOG           1525
#define IDC_BUTTON_BROWSE_LOYLOG        1526
#define IDC_BUTTON_BROWSE_LOYREQ        1527
#define IDC_BUTTON_BROWSE_REQ           1528
#define IDC_BUTTON_CARDNO               1529
#define IDC_BUTTON_CHECK                1530
#define IDC_BUTTON_CLEAR                1531
#define IDC_BUTTON_CLEAR1               1532
#define IDC_BUTTON_CLEAR2               1533
#define IDC_BUTTON_CLONE                1534
#define IDC_BUTTON_COLOUR0              1535
#define IDC_BUTTON_COLOUR1              1536
#define IDC_BUTTON_COLOUR10             1537
#define IDC_BUTTON_COLOUR11             1538
#define IDC_BUTTON_COLOUR12             1539
#define IDC_BUTTON_COLOUR13             1540
#define IDC_BUTTON_COLOUR14             1541
#define IDC_BUTTON_COLOUR15             1542
#define IDC_BUTTON_COLOUR16             1543
#define IDC_BUTTON_COLOUR17             1544
#define IDC_BUTTON_COLOUR2              1545
#define IDC_BUTTON_COLOUR3              1546
#define IDC_BUTTON_COLOUR4              1547
#define IDC_BUTTON_COLOUR5              1548
#define IDC_BUTTON_COLOUR6              1549
#define IDC_BUTTON_COLOUR7              1550
#define IDC_BUTTON_COLOUR8              1551
#define IDC_BUTTON_COLOUR9              1552
#define IDC_BUTTON_CONFIRM              1553
#define IDC_BUTTON_CONSOLIDATE          1554
#define IDC_BUTTON_COPY                 1555
#define IDC_BUTTON_COPYGROUP            1556
#define IDC_BUTTON_DEFAULT              1557
#define IDC_BUTTON_DEFAULT1             1558
#define IDC_BUTTON_DEFAULT2             1559
#define IDC_BUTTON_DELETE               1560
#define IDC_BUTTON_DELETEJSON           1561
#define IDC_BUTTON_DELETEVIEW1          1562
#define IDC_BUTTON_DELETEVIEW2          1563
#define IDC_BUTTON_DELETEVIEW3          1564
#define IDC_BUTTON_DELETE_EXPIRED       1565
#define IDC_BUTTON_DINERMATCH           1566
#define IDC_BUTTON_DISABLE              1567
#define IDC_BUTTON_DISPLAY              1568
#define IDC_BUTTON_DOWN                 1569
#define IDC_BUTTON_EDIT                 1570
#define IDC_BUTTON_EMAILFUNCTIONS       1571
#define IDC_BUTTON_EMAIL_LIST           1572
#define IDC_BUTTON_ERROR                1573
#define IDC_BUTTON_EXCEPTION            1574
#define IDC_BUTTON_EXCEPTIONS           1575
#define IDC_BUTTON_EXECUTE              1576
#define IDC_BUTTON_EXECUTE1             1577
#define IDC_BUTTON_EXECUTE2             1578
#define IDC_BUTTON_EXTREF_TOGGLE        1579
#define IDC_BUTTON_FIELDNAMES           1580
#define IDC_BUTTON_FIELDS               1581
#define IDC_BUTTON_FILESIZE             1582
#define IDC_BUTTON_FIND                 1583
#define IDC_BUTTON_FILESIZE2            1583
#define IDC_BUTTON_GROUPSETS            1584
#define IDC_BUTTON_FILESIZE3            1584
#define IDC_BUTTON_ORPHAN               1584
#define IDC_BUTTON_GROUPSHIFT           1585
#define IDC_BUTTON_IMPORT               1586
#define IDC_BUTTON_IMPORT2              1587
#define IDC_BUTTON_INCLUDEALL           1588
#define IDC_BUTTON_INFO                 1589
#define IDC_BUTTON_INSTALL              1590
#define IDC_BUTTON_INTERFACE            1591
#define IDC_BUTTON_INVERT               1592
#define IDC_BUTTON_LABEL                1593
#define IDC_BUTTON_LIST                 1594
#define IDC_BUTTON_LIST2                1595
#define IDC_BUTTON_LOG                  1596
#define IDC_BUTTON_LOYLOG_FOLDERS       1597
#define IDC_BUTTON_LOYREQ_FOLDERS       1598
#define IDC_BUTTON_MESSAGE_PREVIEW      1599
#define IDC_BUTTON_MODIFY_EXPIRED       1600
#define IDC_BUTTON_MORE                 1601
#define IDC_BUTTON_NEXT                 1602
#define IDC_BUTTON_NONE                 1603
#define IDC_BUTTON_ONDELETE2            1604
#define IDC_BUTTON_OTHER                1605
#define IDC_BUTTON_PASSWORD             1606
#define IDC_BUTTON_PASSWORDS            1607
#define IDC_BUTTON_PAUSE                1608
#define IDC_BUTTON_PAYADD               1609
#define IDC_BUTTON_PAYDELETE            1610
#define IDC_BUTTON_PAYEDIT              1611
#define IDC_BUTTON_PEBBLE               1612
#define IDC_BUTTON_PHOTO                1613
#define IDC_BUTTON_PHOTOID              1614
#define IDC_BUTTON_POINTS_REDEEM        1615
#define IDC_BUTTON_POINTS_TOPUP         1616
#define IDC_BUTTON_PREVIOUS             1617
#define IDC_BUTTON_PRINT                1618
#define IDC_BUTTON_PRINTER              1619
#define IDC_BUTTON_PURSE1_TOPUP         1620
#define IDC_BUTTON_PURSE2_REFRESH       1621
#define IDC_BUTTON_PURSE2_SET           1622
#define IDC_BUTTON_PURSE2_TOPUP         1623
#define IDC_BUTTON_PURSE3_TOPUP         1624
#define IDC_BUTTON_PURSES               1625
#define IDC_BUTTON_RAW                  1626
#define IDC_BUTTON_READER               1627
#define IDC_BUTTON_READER2              1628
#define IDC_BUTTON_REGENERATE           1629
#define IDC_BUTTON_REPORT1              1630
#define IDC_BUTTON_REPORT2              1631
#define IDC_BUTTON_RESEND               1632
#define IDC_BUTTON_RESET                1633
#define IDC_BUTTON_RESTORE              1634
#define IDC_BUTTON_RETRY                1635
#define IDC_BUTTON_RETRYREPORT          1636
#define IDC_BUTTON_RETRYREPORT2         1637
#define IDC_BUTTON_RUN                  1638
#define IDC_BUTTON_SAVE                 1639
#define IDC_BUTTON_SCHEDULE             1640
#define IDC_BUTTON_SEARCHALL            1641
#define IDC_BUTTON_SELECT               1642
#define IDC_BUTTON_SELECTALL            1643
#define IDC_BUTTON_SELECTBALANCES       1644
#define IDC_BUTTON_SET                  1645
#define IDC_BUTTON_SETGROUP             1646
#define IDC_BUTTON_SETTINGS             1647
#define IDC_BUTTON_SETUP                1648
#define IDC_BUTTON_SETUP_AUTOIMPORT     1649
#define IDC_BUTTON_SETUP_CSVIMPORT      1650
#define IDC_BUTTON_SETUP_DELETE         1651
#define IDC_BUTTON_SETUP_EXIT1          1652
#define IDC_BUTTON_SETUP_EXIT2          1653
#define IDC_BUTTON_SETUP_EXIT3          1654
#define IDC_BUTTON_SETUP_SALES          1655
#define IDC_BUTTON_SETUP_SCHEDULE       1656
#define IDC_BUTTON_SETUP_SIMSIMPORT     1657
#define IDC_BUTTON_SETUP_WEBPAYMENT     1658
#define IDC_BUTTON_SETUP_WONDE          1659
#define IDC_BUTTON_SHRINKLOG            1660
#define IDC_BUTTON_SORT                 1661
#define IDC_BUTTON_START                1662
#define IDC_BUTTON_TERMINATE            1663
#define IDC_BUTTON_TEST                 1664
#define IDC_BUTTON_TEST2                1665
#define IDC_BUTTON_TEST_LOG             1666
#define IDC_BUTTON_TEST_LOYLOG          1667
#define IDC_BUTTON_TEST_LOYREQ          1668
#define IDC_BUTTON_TEST_PLU             1669
#define IDC_BUTTON_TEST_REQ             1670
#define IDC_BUTTON_TEST_RULE            1671
#define IDC_BUTTON_TEST_TERMNAME        1672
#define IDC_BUTTON_TRANSFER             1673
#define IDC_BUTTON_UP                   1674
#define IDC_BUTTON_USERS                1675
#define IDC_BUTTON_USERTYPES            1676
#define IDC_BUTTON_VIEW                 1677
#define IDC_BUTTON_VIEW1                1678
#define IDC_BUTTON_VIEW2                1679
#define IDC_BUTTON_VIEW3                1680
#define IDC_BUTTON_VIEW4                1681
#define IDC_BUTTON_ZERO                 1682
#define IDC_CHECK_ACCOUNT1              1683
#define IDC_CHECK_ACCOUNT2              1684
#define IDC_CHECK_ACC_FRI               1685
#define IDC_CHECK_ACC_MON               1686
#define IDC_CHECK_ACC_SAT               1687
#define IDC_CHECK_ACC_SUN               1688
#define IDC_CHECK_ACC_THU               1689
#define IDC_CHECK_ACC_TUE               1690
#define IDC_CHECK_ACC_WED               1691
#define IDC_CHECK_ACTION                1692
#define IDC_CHECK_ACTION1               1693
#define IDC_CHECK_ACTION2               1694
#define IDC_CHECK_ADDPOINTS             1695
#define IDC_CHECK_ADDPOINTSTD           1696
#define IDC_CHECK_ADDPURSE1SPENDTD      1697
#define IDC_CHECK_ADDPURSE1_CREDIT      1698
#define IDC_CHECK_ADDPURSE1_LIABILITY   1699
#define IDC_CHECK_ADDPURSE2SPENDTD      1700
#define IDC_CHECK_ADDPURSE3SPENDTD      1701
#define IDC_CHECK_ADDPURSE3_CREDIT      1702
#define IDC_CHECK_ADDPURSE3_LIABILITY   1703
#define IDC_CHECK_ADDRECORD             1704
#define IDC_CHECK_ADDUNKNOWNS           1705
#define IDC_CHECK_ALERT                 1706
#define IDC_CHECK_ALLERGIES             1707
#define IDC_CHECK_ALLERGY1              1708
#define IDC_CHECK_ALLERGY10             1709
#define IDC_CHECK_ALLERGY11             1710
#define IDC_CHECK_ALLERGY12             1711
#define IDC_CHECK_ALLERGY13             1712
#define IDC_CHECK_ALLERGY14             1713
#define IDC_CHECK_ALLERGY2              1714
#define IDC_CHECK_ALLERGY3              1715
#define IDC_CHECK_ALLERGY4              1716
#define IDC_CHECK_ALLERGY5              1717
#define IDC_CHECK_ALLERGY6              1718
#define IDC_CHECK_ALLERGY7              1719
#define IDC_CHECK_ALLERGY8              1720
#define IDC_CHECK_ALLERGY9              1721
#define IDC_CHECK_ALWAYSALL             1722
#define IDC_CHECK_ALWAYSPROMPT          1723
#define IDC_CHECK_AUTODELETE            1724
#define IDC_CHECK_BATCH                 1725
#define IDC_CHECK_BATCHUPDATES          1726
#define IDC_CHECK_BIOCONSENT            1727
#define IDC_CHECK_CARDLINK              1728
#define IDC_CHECK_CASH                  1729
#define IDC_CHECK_CASHSPEND             1730
#define IDC_CHECK_CLEARCASHSPENDTD      1731
#define IDC_CHECK_CLEARDOB              1732
#define IDC_CHECK_CLEAREXPIRY           1733
#define IDC_CHECK_CLEARGROUP            1734
#define IDC_CHECK_CLEARMAXSPEND         1735
#define IDC_CHECK_CLEAROVERDRAFT        1736
#define IDC_CHECK_CLEARPOINTS           1737
#define IDC_CHECK_CLEARPOINTSTD         1738
#define IDC_CHECK_CLEARPURSE1SPENDTD    1739
#define IDC_CHECK_CLEARPURSE1_CREDIT    1740
#define IDC_CHECK_CLEARPURSE1_LIABILITY 1741
#define IDC_CHECK_CLEARPURSE2SPENDTD    1742
#define IDC_CHECK_CLEARPURSE3SPENDTD    1743
#define IDC_CHECK_CLEARPURSE3_CREDIT    1744
#define IDC_CHECK_CLEARPURSE3_LIABILITY 1745
#define IDC_CHECK_CLEAR_PAYMENT         1746
#define IDC_CHECK_CLEAR_RECENT          1747
#define IDC_CHECK_CONTINUOUS            1748
#define IDC_CHECK_COPYFILES             1749
#define IDC_CHECK_COPYPURCHASES         1750
#define IDC_CHECK_CURRENT_NOEXPIRE      1751
#define IDC_CHECK_DAY1                  1752
#define IDC_CHECK_DAY2                  1753
#define IDC_CHECK_DAY3                  1754
#define IDC_CHECK_DAY4                  1755
#define IDC_CHECK_DAY5                  1756
#define IDC_CHECK_DAY6                  1757
#define IDC_CHECK_DAY7                  1758
#define IDC_CHECK_DELETEFILE            1759
#define IDC_CHECK_DELETEFILE2           1760
#define IDC_CHECK_DELETERECORD          1761
#define IDC_CHECK_DELPCTRL              1762
#define IDC_CHECK_DIETARY               1763
#define IDC_CHECK_DELPCTRL2             1763
#define IDC_CHECK_PINNUMBER             1763
#define IDC_CHECK_DISABLEREDEEM         1764
#define IDC_CHECK_DISABLESTAFF          1765
#define IDC_CHECK_DOB                   1766
#define IDC_CHECK_EDITEXTERNAL          1767
#define IDC_CHECK_EDITGENERAL           1768
#define IDC_CHECK_EDITPOINTS            1769
#define IDC_CHECK_EDITPURSE             1770
#define IDC_CHECK_EMAIL                 1771
#define IDC_CHECK_EMAILLOWBALANCEALERT  1772
#define IDC_CHECK_EMAILPOINTSACHIEVEMENT 1773
#define IDC_CHECK_EMAILPURCHASES        1774
#define IDC_CHECK_EMAILWEEKLYPOINTS     1775
#define IDC_CHECK_ENABLE                1776
#define IDC_CHECK_ENABLEBACKGROUND      1777
#define IDC_CHECK_ENABLELOGOFF          1778
#define IDC_CHECK_ENABLENOAUDIT         1779
#define IDC_CHECK_ENABLEPHOTOID         1780
#define IDC_CHECK_ENABLEPOINTS          1781
#define IDC_CHECK_ENABLEPURSE3          1782
#define IDC_CHECK_ENABLETOPUP           1783
#define IDC_CHECK_ENABLE_AUTOIMPORT     1784
#define IDC_CHECK_ENABLE_CHARTWELLS     1785
#define IDC_CHECK_ENABLE_SIMSIMPORT     1786
#define IDC_CHECK_ENABLE_WONDE          1787
#define IDC_CHECK_EOD                   1788
#define IDC_CHECK_EODAFTERPAYMENTS      1789
#define IDC_CHECK_EPOSAWARD             1790
#define IDC_CHECK_EXCLUDE1              1792
#define IDC_CHECK_EXCLUDE2              1793
#define IDC_CHECK_EXCLUDE3              1794
#define IDC_CHECK_EXCLUDE4              1795
#define IDC_CHECK_EXCLUDENOCHANGE       1796
#define IDC_CHECK_EXCLUDEPAYMENTS       1797
#define IDC_CHECK_EXCLUDEPERIOD         1798
#define IDC_CHECK_EXCLUDESALESBREAKDOWN 1799
#define IDC_CHECK_EXCLUDEZERO           1800
#define IDC_CHECK_EXCLUDZERO            1801
#define IDC_CHECK_EXPIRED               1802
#define IDC_CHECK_EXPIRY                1803
#define IDC_CHECK_EXPORT                1804
#define IDC_CHECK_EXPORTBALANCES        1805
#define IDC_CHECK_EXPORTPHOTO           1806
#define IDC_CHECK_EXPORTPURSE2          1807
#define IDC_CHECK_EXPORTUPDATES         1808
#define IDC_CHECK_EXPORT_DELETE         1809
#define IDC_CHECK_EXPORT_EXIT           1810
#define IDC_CHECK_EXPORT_SALES          1811
#define IDC_CHECK_EXTERNAL              1812
#define IDC_CHECK_EXTREF2               1813
#define IDC_CHECK_FORENAME              1814
#define IDC_CHECK_FRIDAY                1815
#define IDC_CHECK_FROM                  1816
#define IDC_CHECK_GROUPNO               1817
#define IDC_CHECK_GROUPREDEEM           1818
#define IDC_CHECK_GROUPSETS             1819
#define IDC_CHECK_GROUPSHIFT_CURRENT    1820
#define IDC_CHECK_GROUPSHIFT_FUTURE     1821
#define IDC_CHECK_GROUPSHIFT_NONE       1822
#define IDC_CHECK_GROUPSORT             1823
#define IDC_CHECK_GS_DATERANGE          1824
#define IDC_CHECK_GS_ONDUTY             1825
#define IDC_CHECK_HISTORY               1826
#define IDC_CHECK_HISTORY_DISABLEACZERO 1827
#define IDC_CHECK_HOTLIST               1828
#define IDC_CHECK_HOUR0                 1829
#define IDC_CHECK_HOUR1                 1830
#define IDC_CHECK_HOUR10                1831
#define IDC_CHECK_HOUR11                1832
#define IDC_CHECK_HOUR12                1833
#define IDC_CHECK_HOUR13                1834
#define IDC_CHECK_HOUR14                1835
#define IDC_CHECK_HOUR15                1836
#define IDC_CHECK_HOUR16                1837
#define IDC_CHECK_HOUR17                1838
#define IDC_CHECK_HOUR18                1839
#define IDC_CHECK_HOUR19                1840
#define IDC_CHECK_HOUR2                 1841
#define IDC_CHECK_HOUR20                1842
#define IDC_CHECK_HOUR21                1843
#define IDC_CHECK_HOUR22                1844
#define IDC_CHECK_HOUR23                1845
#define IDC_CHECK_HOUR3                 1846
#define IDC_CHECK_HOUR4                 1847
#define IDC_CHECK_HOUR5                 1848
#define IDC_CHECK_HOUR6                 1849
#define IDC_CHECK_HOUR7                 1850
#define IDC_CHECK_HOUR8                 1851
#define IDC_CHECK_HOUR9                 1852
#define IDC_CHECK_IGNORECASE            1853
#define IDC_CHECK_IMPORT                1854
#define IDC_CHECK_IMPORTACCOUNTS        1855
#define IDC_CHECK_IMPORTPAYMENTS        1856
#define IDC_CHECK_IMPORTPAYMENTS2       1857
#define IDC_CHECK_IMP_FRI               1858
#define IDC_CHECK_IMP_MON               1859
#define IDC_CHECK_IMP_SAT               1860
#define IDC_CHECK_IMP_SUN               1861
#define IDC_CHECK_IMP_THU               1862
#define IDC_CHECK_IMP_TUE               1863
#define IDC_CHECK_IMP_WED               1864
#define IDC_CHECK_INACTIVE              1865
#define IDC_CHECK_INCLUDEPURSE2         1866
#define IDC_CHECK_INFO1                 1867
#define IDC_CHECK_INFO2                 1868
#define IDC_CHECK_INFO3                 1869
#define IDC_CHECK_INFO4                 1870
#define IDC_CHECK_INFO5                 1871
#define IDC_CHECK_INFO6                 1872
#define IDC_CHECK_INFO7                 1873
#define IDC_CHECK_INFO8                 1874
#define IDC_CHECK_INSTALLBGND           1875
#define IDC_CHECK_INSTALLSERVER         1876
#define IDC_CHECK_KEEPLINKLOG           1877
#define IDC_CHECK_KEEPXMLFILES          1878
#define IDC_CHECK_KEEPXMLLOGIN          1879
#define IDC_CHECK_KIOSKREVAL            1880
#define IDC_CHECK_LEAVERSDATABASE       1881
#define IDC_CHECK_LOGACTION2            1882
#define IDC_CHECK_LOGON                 1883
#define IDC_CHECK_LOOKUP_BIO            1884
#define IDC_CHECK_LOOKUP_DEFAULT        1885
#define IDC_CHECK_LOOKUP_INTERNAL       1886
#define IDC_CHECK_LOOKUP_MANUAL         1887
#define IDC_CHECK_LOOKUP_OTHER          1888
#define IDC_CHECK_LOOKUP_SCAN           1889
#define IDC_CHECK_LOOKUP_UNKNOWN        1890
#define IDC_CHECK_MANUALADD             1891
#define IDC_CHECK_MANUALDELETE          1892
#define IDC_CHECK_MANUALEDIT            1893
#define IDC_CHECK_MAXSPEND              1894
#define IDC_CHECK_MAXSPEND_COPY         1895
#define IDC_CHECK_MAXSPEND_MODIFY       1896
#define IDC_CHECK_MEMBERID              1897
#define IDC_CHECK_MESSAGE               1898
#define IDC_CHECK_MODIFYRECORD          1899
#define IDC_CHECK_MONDAY                1900
#define IDC_CHECK_MONTH1                1901
#define IDC_CHECK_MONTH10               1902
#define IDC_CHECK_MONTH11               1903
#define IDC_CHECK_MONTH12               1904
#define IDC_CHECK_MONTH2                1905
#define IDC_CHECK_MONTH3                1906
#define IDC_CHECK_MONTH4                1907
#define IDC_CHECK_MONTH5                1908
#define IDC_CHECK_MONTH6                1909
#define IDC_CHECK_MONTH7                1910
#define IDC_CHECK_MONTH8                1911
#define IDC_CHECK_MONTH9                1912
#define IDC_CHECK_MON_FRI               1913
#define IDC_CHECK_NEWBALANCE            1914
#define IDC_CHECK_NEWPAGE               1915
#define IDC_CHECK_NOEXPIRY              1916
#define IDC_CHECK_NOZEROSKIP            1917
#define IDC_CHECK_OVERDRAFT             1918
#define IDC_CHECK_OWNMAXSPEND           1919
#define IDC_CHECK_P1_PURSE1             1920
#define IDC_CHECK_P1_PURSE2             1921
#define IDC_CHECK_P1_PURSE3             1922
#define IDC_CHECK_P2_PURSE1             1923
#define IDC_CHECK_P2_PURSE2             1924
#define IDC_CHECK_P2_PURSE3             1925
#define IDC_CHECK_P3_PURSE1             1926
#define IDC_CHECK_P3_PURSE2             1927
#define IDC_CHECK_P3_PURSE3             1928
#define IDC_CHECK_P4_PURSE1             1929
#define IDC_CHECK_P4_PURSE2             1930
#define IDC_CHECK_P4_PURSE3             1931
#define IDC_CHECK_P5_PURSE1             1932
#define IDC_CHECK_P5_PURSE2             1933
#define IDC_CHECK_P5_PURSE3             1934
#define IDC_CHECK_P6_PURSE1             1935
#define IDC_CHECK_P6_PURSE2             1936
#define IDC_CHECK_P6_PURSE3             1937
#define IDC_CHECK_PASSWORD              1938
#define IDC_CHECK_PASSWORDS             1939
#define IDC_CHECK_PHOTOID               1940
#define IDC_CHECK_POINTS                1941
#define IDC_CHECK_POINTSTD              1942
#define IDC_CHECK_POUNDPURSE1           1943
#define IDC_CHECK_POUNDPURSE2           1944
#define IDC_CHECK_POUNDPURSE3           1945
#define IDC_CHECK_PRICELEVEL            1946
#define IDC_CHECK_PROMPT                1947
#define IDC_CHECK_PROMPTBEFOREACCESS    1948
#define IDC_CHECK_PROMPTCANCEL          1949
#define IDC_CHECK_PURCHASECONTROL       1950
#define IDC_CHECK_PROMPTCANCEL2         1950
#define IDC_CHECK_AUDITIMPORTFILTER     1950
#define IDC_CHECK_PURSE1                1952
#define IDC_CHECK_PURSE1SPEND           1953
#define IDC_CHECK_PURSE1SPENDTD         1954
#define IDC_CHECK_PURSE1_CREDIT         1955
#define IDC_CHECK_PURSE1_LIABILITY      1956
#define IDC_CHECK_PURSE2                1957
#define IDC_CHECK_PURSE2SPEND           1958
#define IDC_CHECK_PURSE2SPENDTD         1959
#define IDC_CHECK_PURSE2_APPEND         1960
#define IDC_CHECK_PURSE3                1961
#define IDC_CHECK_PURSE3SPEND           1962
#define IDC_CHECK_PURSE3SPENDTD         1963
#define IDC_CHECK_PURSE3_CREDIT         1964
#define IDC_CHECK_PURSE3_LIABILITY      1965
#define IDC_CHECK_RECORDTICK1           1966
#define IDC_CHECK_RECORDTICK2           1967
#define IDC_CHECK_RECORDTICK3           1968
#define IDC_CHECK_RECORDTICK4           1969
#define IDC_CHECK_REDEEMDISABLEAUTO     1970
#define IDC_CHECK_REPLYTO               1971
#define IDC_CHECK_REPORTS               1972
#define IDC_CHECK_REVALUATIONTYPE       1973
#define IDC_CHECK_REVALUEDISABLED       1974
#define IDC_CHECK_REWARDDISABLED        1975
#define IDC_CHECK_REWARDTYPE            1976
#define IDC_CHECK_SATURDAY              1977
#define IDC_CHECK_SAVEEMAIL             1978
#define IDC_CHECK_SAVEEMAIL2            1979
#define IDC_CHECK_SETALERT              1980
#define IDC_CHECK_SETDOB                1981
#define IDC_CHECK_SETEXPIRY             1982
#define IDC_CHECK_SETGROUP              1983
#define IDC_CHECK_SETNAME               1984
#define IDC_CHECK_SETUPBGND             1985
#define IDC_CHECK_SETUPSERVER           1986
#define IDC_CHECK_SETUPSYSTEM           1987
#define IDC_CHECK_SHOWCASHBUTTON        1988
#define IDC_CHECK_SHOWECRTEXT           1989
#define IDC_CHECK_SHOWEODLINES          1990
#define IDC_CHECK_SHOWEXTLINES          1991
#define IDC_CHECK_SHOWNAME              1992
#define IDC_CHECK_SHOWPCLINES           1993
#define IDC_CHECK_SHOWPOINTS            1994
#define IDC_CHECK_SHOWPOINTSBUTTON      1995
#define IDC_CHECK_SHOWPOSLINES          1996
#define IDC_CHECK_SHOWPURCHASES         1997
#define IDC_CHECK_SHOWPURSE1            1998
#define IDC_CHECK_SHOWPURSE2            1999
#define IDC_CHECK_SHOWPURSE3            2000
#define IDC_CHECK_SHOWREMOVED           2001
#define IDC_CHECK_SHOWSERVERLINES       2002
#define IDC_CHECK_SHOWUNUSED            2003
#define IDC_CHECK_SHOW_PREVIOUS         2004
#define IDC_CHECK_SINGLE                2005
#define IDC_CHECK_SKIPONBLANK           2006
#define IDC_CHECK_SMTPDIRECT            2007
#define IDC_CHECK_SORT                  2008
#define IDC_CHECK_SORTBYCARDNO          2009
#define IDC_CHECK_SORTBYGROUP           2010
#define IDC_CHECK_SORTDATE              2011
#define IDC_CHECK_SORTGROUP             2012
#define IDC_CHECK_SORTID                2013
#define IDC_CHECK_SOURCE_BACKGROUND     2014
#define IDC_CHECK_SOURCE_MANAGER        2015
#define IDC_CHECK_SOURCE_MANUAL         2016
#define IDC_CHECK_SOURCE_SERVER         2017
#define IDC_CHECK_SSL                   2018
#define IDC_CHECK_START                 2019
#define IDC_CHECK_STATUSCOLOUR          2020
#define IDC_CHECK_STOP                  2021
#define IDC_CHECK_SUMMARY               2022
#define IDC_CHECK_SUNDAY                2023
#define IDC_CHECK_SURNAME               2024
#define IDC_CHECK_TERMINALS             2025
#define IDC_CHECK_TESTMODE              2026
#define IDC_CHECK_THISPC                2027
#define IDC_CHECK_THURSDAY              2028
#define IDC_CHECK_TICK1                 2029
#define IDC_CHECK_TICK2                 2030
#define IDC_CHECK_TICK3                 2031
#define IDC_CHECK_TICK4                 2032
#define IDC_CHECK_TOTALISE              2033
#define IDC_CHECK_TRANSFER              2034
#define IDC_CHECK_TRANSFERRECORD        2035
#define IDC_CHECK_TRIMZERO_EXTREF1      2036
#define IDC_CHECK_TUESDAY               2037
#define IDC_CHECK_UNISSUED              2038
#define IDC_CHECK_UNKNOWN               2039
#define IDC_CHECK_USERNAME              2040
#define IDC_CHECK_VALID                 2041
#define IDC_CHECK_VATSHIFT              2042
#define IDC_CHECK_VENDING               2043
#define IDC_CHECK_WEBPAYMENT            2044
#define IDC_CHECK_WEBSUSPEND            2045
#define IDC_CHECK_WEDNESDAY             2046
#define IDC_CHECK_ZEROSKIP              2047
#define IDC_COLOURBUTTON_MESSAGEBACK    2048
#define IDC_COLOURBUTTON_MESSAGETEXT    2049
#define IDC_COMBO_ACCESSTYPE            2050
#define IDC_COMBO_ACCOUNT1              2051
#define IDC_COMBO_ACCOUNT2              2052
#define IDC_COMBO_ADDITIONALREFFIELD    2053
#define IDC_COMBO_AND                   2054
#define IDC_COMBO_BAUD                  2055
#define IDC_COMBO_BIOCONSENT            2056
#define IDC_COMBO_BIOREGISTRY           2057
#define IDC_COMBO_COMMENT               2058
#define IDC_COMBO_COMMENTS              2059
#define IDC_COMBO_COMPRESSION           2060
#define IDC_COMBO_CONDITION1            2061
#define IDC_COMBO_CONDITION2            2062
#define IDC_COMBO_CONDITION3            2063
#define IDC_COMBO_CSVFORMAT             2064
#define IDC_COMBO_DAILYSPEND            2065
#define IDC_COMBO_DATERANGE             2066
#define IDC_COMBO_DEFAULTFORMAT         2067
#define IDC_COMBO_DELPCTRL              2068
#define IDC_COMBO_DOB                   2069
#define IDC_COMBO_DURATION              2070
#define IDC_COMBO_EMAIL                 2071
#define IDC_COMBO_EMAIL5                2072
#define IDC_COMBO_EMAILCONTACTNO        2073
#define IDC_COMBO_EXTREF1               2074
#define IDC_COMBO_EXTREF2               2075
#define IDC_COMBO_FIELD1                2076
#define IDC_COMBO_FIELD2                2077
#define IDC_COMBO_FIELD3                2078
#define IDC_COMBO_FIELD4                2079
#define IDC_COMBO_FIELD5                2080
#define IDC_COMBO_FIELD6                2081
#define IDC_COMBO_FIELDNAMES            2082
#define IDC_COMBO_FOLDERSET             2083
#define IDC_COMBO_FORENAME              2084
#define IDC_COMBO_FORMAT1               2085
#define IDC_COMBO_FORMAT2               2086
#define IDC_COMBO_FORMNAME              2087
#define IDC_COMBO_GENDER                2088
#define IDC_COMBO_GROUP                 2089
#define IDC_COMBO_GROUP1                2090
#define IDC_COMBO_GROUP2                2091
#define IDC_COMBO_GROUPSHIFT            2092
#define IDC_COMBO_HOUSE                 2093
#define IDC_COMBO_INFO                  2094
#define IDC_COMBO_INFOFILTER            2095
#define IDC_COMBO_INTERFACE             2096
#define IDC_COMBO_LABELS                2097
#define IDC_COMBO_LIBS                  2098
#define IDC_COMBO_LOCATE                2099
#define IDC_COMBO_LOCATEBY              2100
#define IDC_COMBO_LOCATEON              2101
#define IDC_COMBO_LOGOFF                2102
#define IDC_COMBO_MESSAGE_FONT          2103
#define IDC_COMBO_MESSAGE_SPACE         2104
#define IDC_COMBO_MINUTE_CUSTOM         2105
#define IDC_COMBO_MINUTE_HOURLY         2106
#define IDC_COMBO_MISID                 2107
#define IDC_COMBO_MODIFY                2108
#define IDC_COMBO_NEWEXPIRY             2109
#define IDC_COMBO_NEWINTAKE             2110
#define IDC_COMBO_NEWINTAKE2            2111
#define IDC_COMBO_NEWINTAKEPUPIL        2112
#define IDC_COMBO_NEWINTAKESTAFF        2113
#define IDC_COMBO_OFFICEVAT             2114
#define IDC_COMBO_ORDERBY               2115
#define IDC_COMBO_OUTPUT                2116
#define IDC_COMBO_OVERRIDE              2117
#define IDC_COMBO_PAGE                  2118
#define IDC_COMBO_PAYMENTS              2119
#define IDC_COMBO_PID                   2120
#define IDC_COMBO_PORT                  2121
#define IDC_COMBO_PREVIOUS              2122
#define IDC_COMBO_PROMPT                2123
#define IDC_COMBO_PROMPT2               2124
#define IDC_COMBO_PURSE                 2125
#define IDC_COMBO_PURSE2_P1             2126
#define IDC_COMBO_PURSE2_P2             2127
#define IDC_COMBO_PURSE2_P3             2128
#define IDC_COMBO_PURSE2_P4             2129
#define IDC_COMBO_PURSE2_P5             2130
#define IDC_COMBO_PURSE2_P6             2131
#define IDC_COMBO_PURSE2_TYPE           2132
#define IDC_COMBO_RANKBY                2133
#define IDC_COMBO_READER                2134
#define IDC_COMBO_REASON                2135
#define IDC_COMBO_REG                   2136
#define IDC_COMBO_RULE                  2137
#define IDC_COMBO_SIMS                  2138
#define IDC_COMBO_SOAP                  2139
#define IDC_COMBO_SORTON                2140
#define IDC_COMBO_SPOSTYPE              2141
#define IDC_COMBO_SQUIDCARD             2142
#define IDC_COMBO_SQUIDCVV              2143
#define IDC_COMBO_SQUIDEXTREFERENCE     2144
#define IDC_COMBO_SQUIDPUPILID          2145
#define IDC_COMBO_STARTOFWEEK           2146
#define IDC_COMBO_SUMMARY               2148
#define IDC_COMBO_TERMINALS             2149
#define IDC_COMBO_TIMERANGE             2150
#define IDC_COMBO_TOPUPTYPE             2151
#define IDC_COMBO_UPN                   2152
#define IDC_COMBO_USERTYPE              2153
#define IDC_COMBO_VATCODEA              2154
#define IDC_COMBO_VATCODEB              2155
#define IDC_COMBO_VATCODEC              2156
#define IDC_COMBO_VATCODED              2157
#define IDC_COMBO_VATCODEE              2158
#define IDC_COMBO_VATCODEF              2159
#define IDC_COMBO_VATCODEG              2160
#define IDC_COMBO_VATCODEH              2161
#define IDC_COMBO_VATCODEI              2162
#define IDC_COMBO_VATCODEJ              2163
#define IDC_COMBO_VATCODEK              2164
#define IDC_COMBO_VATCODEL              2165
#define IDC_COMBO_WEBPAYMENT            2166
#define IDC_COMBO_WEBPAYMENT2           2167
#define IDC_COMBO_WEEKDAY               2168
#define IDC_COMBO_YEAR                  2169
#define IDC_DATEPICKER_AWARD            2170
#define IDC_DATEPICKER_CURRENT_FROM     2171
#define IDC_DATEPICKER_CURRENT_TO       2172
#define IDC_DATEPICKER_END              2173
#define IDC_DATEPICKER_EXPIRY           2174
#define IDC_DATEPICKER_FROM             2175
#define IDC_DATEPICKER_FROM_SALE        2176
#define IDC_DATEPICKER_FROM_TOPUP       2177
#define IDC_DATEPICKER_NEW              2178
#define IDC_DATEPICKER_START            2179
#define IDC_DATEPICKER_TO               2180
#define IDC_DATETIMEPICKER1             2181
#define IDC_DATETIMEPICKER10            2182
#define IDC_DATETIMEPICKER11            2183
#define IDC_DATETIMEPICKER12            2184
#define IDC_DATETIMEPICKER13            2185
#define IDC_DATETIMEPICKER2             2187
#define IDC_DATETIMEPICKER3             2188
#define IDC_DATETIMEPICKER4             2189
#define IDC_DATETIMEPICKER5             2190
#define IDC_DATETIMEPICKER6             2191
#define IDC_DATETIMEPICKER7             2192
#define IDC_DATETIMEPICKER8             2193
#define IDC_DATETIMEPICKER9             2194
#define IDC_DATETIMEPICKER_ACC1         2195
#define IDC_DATETIMEPICKER_ACC2         2196
#define IDC_DATETIMEPICKER_DOB          2197
#define IDC_DATETIMEPICKER_EXPIRY       2198
#define IDC_DATETIMEPICKER_FRIE         2199
#define IDC_DATETIMEPICKER_FRIS         2200
#define IDC_DATETIMEPICKER_MONE         2201
#define IDC_DATETIMEPICKER_MONS         2202
#define IDC_DATETIMEPICKER_SATE         2203
#define IDC_DATETIMEPICKER_SATS         2204
#define IDC_DATETIMEPICKER_SUNE         2205
#define IDC_DATETIMEPICKER_SUNS         2206
#define IDC_DATETIMEPICKER_THUE         2207
#define IDC_DATETIMEPICKER_THUS         2208
#define IDC_DATETIMEPICKER_TUEE         2209
#define IDC_DATETIMEPICKER_TUES         2210
#define IDC_DATETIMEPICKER_WEDE         2211
#define IDC_DATETIMEPICKER_WEDS         2212
#define IDC_EDIT_ACTIVE_ID              2213
#define IDC_EDIT_ACTIVE_TIME            2214
#define IDC_EDIT_ADDPURSE1              2215
#define IDC_EDIT_ADDPURSE2              2216
#define IDC_EDIT_ADDRESS_FROM           2217
#define IDC_EDIT_ADJUSTSTART            2218
#define IDC_EDIT_ALERT                  2219
#define IDC_EDIT_ALERTTEXT              2220
#define IDC_EDIT_ALLERGIES              2221
#define IDC_EDIT_ATCARCHIVECOUNT        2222
#define IDC_EDIT_ATCARCHIVEDATES        2223
#define IDC_EDIT_ATCARCHIVEENTRIES      2224
#define IDC_EDIT_ATCARCHIVELINES        2225
#define IDC_EDIT_ATTEMPT                2226
#define IDC_EDIT_AVAILABLE              2227
#define IDC_EDIT_BALANCE                2228
#define IDC_EDIT_BALANCE1               2229
#define IDC_EDIT_BALANCE2               2230
#define IDC_EDIT_BALANCE3               2231
#define IDC_EDIT_BALANCE4               2232
#define IDC_EDIT_BALANCE5               2233
#define IDC_EDIT_BALANCE6               2234
#define IDC_EDIT_BIOCONSENT             2235
#define IDC_EDIT_BIOREG                 2236
#define IDC_EDIT_BLUE                   2237
#define IDC_EDIT_CACHE                  2238
#define IDC_EDIT_CARDNAME               2239
#define IDC_EDIT_CARDNO                 2240
#define IDC_EDIT_CARDNO_FROM            2241
#define IDC_EDIT_CARDNO_PUPIL           2242
#define IDC_EDIT_CARDNO_STAFF           2243
#define IDC_EDIT_CARDNO_TO              2244
#define IDC_EDIT_CASH                   2245
#define IDC_EDIT_CLEAR_PAYMENT          2246
#define IDC_EDIT_CLEAR_RECENT           2247
#define IDC_EDIT_COMMENT                2248
#define IDC_EDIT_COMMENT_DOWN           2249
#define IDC_EDIT_COMMENT_UP             2250
#define IDC_EDIT_COUNT                  2251
#define IDC_EDIT_CREDITADJUSTDOWN       2252
#define IDC_EDIT_CREDITADJUSTUP         2253
#define IDC_EDIT_CUSTOMFIELD            2254
#define IDC_EDIT_DATE1                  2255
#define IDC_EDIT_DATE10                 2256
#define IDC_EDIT_DATE11                 2257
#define IDC_EDIT_DATE2                  2258
#define IDC_EDIT_DATE3                  2259
#define IDC_EDIT_DATE4                  2260
#define IDC_EDIT_DATE5                  2261
#define IDC_EDIT_DATE6                  2262
#define IDC_EDIT_DATE7                  2263
#define IDC_EDIT_DEDUCT4                2264
#define IDC_EDIT_DEPTSINHIBITED         2265
#define IDC_EDIT_DIETARY                2266
#define IDC_EDIT_DOB                    2267
#define IDC_EDIT_ECRMANPATH             2268
#define IDC_EDIT_EMAIL                  2269
#define IDC_EDIT_EMAILSIGNATURE         2270
#define IDC_EDIT_EMAILTEXT              2271
#define IDC_EDIT_ENDTEXT                2272
#define IDC_EDIT_EPOSPHOTOFOLDER        2273
#define IDC_EDIT_ERROR                  2274
#define IDC_EDIT_EXCEPTIONS             2275
#define IDC_EDIT_EXTREF                 2276
#define IDC_EDIT_EXTREF2                2277
#define IDC_EDIT_FIELD1                 2278
#define IDC_EDIT_FIELD2                 2279
#define IDC_EDIT_FIELD3                 2280
#define IDC_EDIT_FIELD4                 2281
#define IDC_EDIT_FIELD5                 2282
#define IDC_EDIT_FIELD6                 2283
#define IDC_EDIT_FIELD7                 2284
#define IDC_EDIT_FIELD8                 2285
#define IDC_EDIT_FIELD9                 2286
#define IDC_EDIT_FIELDTEXT1             2287
#define IDC_EDIT_FIELDTEXT2             2288
#define IDC_EDIT_FIELDTEXT3             2289
#define IDC_EDIT_FIELDTEXT4             2290
#define IDC_EDIT_FIELDTEXT5             2291
#define IDC_EDIT_FIELDTEXT6             2292
#define IDC_EDIT_FILENAME               2293
#define IDC_EDIT_FIND                   2294
#define IDC_EDIT_FINDSTRING             2295
#define IDC_EDIT_FOLDER                 2296
#define IDC_EDIT_FORENAME               2297
#define IDC_EDIT_FROMCARDNO             2298
#define IDC_EDIT_GENERAL_BALANCE        2299
#define IDC_EDIT_GENERAL_CASHSPEND      2300
#define IDC_EDIT_GREEN                  2301
#define IDC_EDIT_GROUPDAY1              2302
#define IDC_EDIT_GROUPDAY2              2303
#define IDC_EDIT_GROUPDAY3              2304
#define IDC_EDIT_GROUPDAY4              2305
#define IDC_EDIT_GROUPDAY5              2306
#define IDC_EDIT_GROUPDAY6              2307
#define IDC_EDIT_GROUPDAY7              2308
#define IDC_EDIT_GROUPNAME              2309
#define IDC_EDIT_GROUPNO                2310
#define IDC_EDIT_GROUPSHIFT             2311
#define IDC_EDIT_HEADER                 2312
#define IDC_EDIT_IMPORTFILE             2313
#define IDC_EDIT_IMPORTFILENAME         2314
#define IDC_EDIT_IMPORTREFUND           2315
#define IDC_EDIT_IMPORTTOPUP            2316
#define IDC_EDIT_INFO1                  2317
#define IDC_EDIT_INFO2                  2318
#define IDC_EDIT_INFO3                  2319
#define IDC_EDIT_INFO4                  2320
#define IDC_EDIT_INFO5                  2321
#define IDC_EDIT_INFO6                  2322
#define IDC_EDIT_INFO7                  2323
#define IDC_EDIT_INFO8                  2324
#define IDC_EDIT_INSTID                 2325
#define IDC_EDIT_INTERVAL               2326
#define IDC_EDIT_IPADDRESS              2327
#define IDC_EDIT_KIOSKNO                2328
#define IDC_EDIT_KIOSKTOPUP             2329
#define IDC_EDIT_LAST                   2330
#define IDC_EDIT_LASTPAYMENT            2331
#define IDC_EDIT_LASTPAYMENT2           2332
#define IDC_EDIT_LASTPAYMENTID          2333
#define IDC_EDIT_LASTPAYMENTID2         2334
#define IDC_EDIT_LINESIGNORED           2335
#define IDC_EDIT_LINESINVALID           2336
#define IDC_EDIT_LINESREAD              2337
#define IDC_EDIT_LINESUSED              2338
#define IDC_EDIT_LINESVALID             2339
#define IDC_EDIT_LIST1                  2340
#define IDC_EDIT_LIST2                  2341
#define IDC_EDIT_LIST3                  2342
#define IDC_EDIT_LIST4                  2343
#define IDC_EDIT_LOYLOGPATH             2344
#define IDC_EDIT_LOYREQPATH             2345
#define IDC_EDIT_MAXSPEND               2346
#define IDC_EDIT_MAXSPEND1              2347
#define IDC_EDIT_MAXSPEND1P3            2348
#define IDC_EDIT_MAXSPEND2              2349
#define IDC_EDIT_MAXSPEND2P3            2350
#define IDC_EDIT_MAXSPEND3              2351
#define IDC_EDIT_MAXSPEND3P3            2352
#define IDC_EDIT_MAXSPEND4              2353
#define IDC_EDIT_MAXSPEND4P3            2354
#define IDC_EDIT_MAXSPEND5              2355
#define IDC_EDIT_MAXSPEND5P3            2356
#define IDC_EDIT_MAXSPEND6              2357
#define IDC_EDIT_MAXSPEND6P3            2358
#define IDC_EDIT_MAXSPENDP1             2359
#define IDC_EDIT_MAXSPENDP3             2360
#define IDC_EDIT_MAXUSERS               2361
#define IDC_EDIT_MEALSESSION1           2362
#define IDC_EDIT_MEALSESSION2           2363
#define IDC_EDIT_MEALVALUE              2364
#define IDC_EDIT_MEMBERID               2365
#define IDC_EDIT_MEMORABLE              2366
#define IDC_EDIT_MENUTEXT               2367
#define IDC_EDIT_MIFARE                 2368
#define IDC_EDIT_MINUTES2               2369
#define IDC_EDIT_MINUTES3               2370
#define IDC_EDIT_MONTHDAY               2371
#define IDC_EDIT_MULTIPLIERFACTOR_FRI   2372
#define IDC_EDIT_MULTIPLIERFACTOR_MON   2373
#define IDC_EDIT_MULTIPLIERFACTOR_SAT   2374
#define IDC_EDIT_MULTIPLIERFACTOR_SUN   2375
#define IDC_EDIT_MULTIPLIERFACTOR_THU   2376
#define IDC_EDIT_MULTIPLIERFACTOR_TUE   2377
#define IDC_EDIT_MULTIPLIERFACTOR_WED   2378
#define IDC_EDIT_MULTIPLIERTRIGGER      2379
#define IDC_EDIT_NAME                   2380
#define IDC_EDIT_NEVER                  2381
#define IDC_EDIT_NEXT                   2382
#define IDC_EDIT_NEXTCARDNO             2383
#define IDC_EDIT_NEXTID                 2384
#define IDC_EDIT_OFFICEADJUSTMENT       2385
#define IDC_EDIT_OFFICEDELETION         2386
#define IDC_EDIT_OFFICEMEAL             2387
#define IDC_EDIT_OFFICEPLU              2388
#define IDC_EDIT_OFFICEREFUND           2389
#define IDC_EDIT_OFFICESALEADJUSTMENT   2390
#define IDC_EDIT_OFFICETOPUP            2391
#define IDC_EDIT_OFFLINELIMIT           2392
#define IDC_EDIT_OFFLINESPENDID         2393
#define IDC_EDIT_ORGID                  2394
#define IDC_EDIT_OVERSPEND              2395
#define IDC_EDIT_OVERSPEND1             2396
#define IDC_EDIT_OVERSPEND1P3           2397
#define IDC_EDIT_OVERSPEND2             2398
#define IDC_EDIT_OVERSPEND2P3           2399
#define IDC_EDIT_OVERSPEND3             2400
#define IDC_EDIT_OVERSPEND3P3           2401
#define IDC_EDIT_OVERSPEND4             2402
#define IDC_EDIT_OVERSPEND4P3           2403
#define IDC_EDIT_OVERSPEND5             2404
#define IDC_EDIT_OVERSPEND5P3           2405
#define IDC_EDIT_OVERSPEND6             2406
#define IDC_EDIT_OVERSPEND6P3           2407
#define IDC_EDIT_OVERSPENDP1            2408
#define IDC_EDIT_OVERSPENDP3            2409
#define IDC_EDIT_PASSWORD               2410
#define IDC_EDIT_PCID                   2412
#define IDC_EDIT_PEBBLEORDER            2413
#define IDC_EDIT_PEBBLEORDERREFUND      2414
#define IDC_EDIT_PERIODTEXT1            2415
#define IDC_EDIT_PERIODTEXT2            2416
#define IDC_EDIT_PERIODTEXT3            2417
#define IDC_EDIT_PERIODTEXT4            2418
#define IDC_EDIT_PERIODTEXT5            2419
#define IDC_EDIT_PERIODTEXT6            2420
#define IDC_EDIT_PHOTOFOLDER            2421
#define IDC_EDIT_PLUDATAPATH            2422
#define IDC_EDIT_PLU_PURSE1             2423
#define IDC_EDIT_PLU_PURSE3             2424
#define IDC_EDIT_POINTS                 2425
#define IDC_EDIT_POINTS1                2426
#define IDC_EDIT_POINTS2                2427
#define IDC_EDIT_POINTSACHIEVEMENT      2428
#define IDC_EDIT_POINTSBALANCE          2429
#define IDC_EDIT_POINTSTD               2430
#define IDC_EDIT_POINTSVALUE            2431
#define IDC_EDIT_POINTS_BALANCE         2432
#define IDC_EDIT_POINTS_TODATE          2433
#define IDC_EDIT_POINTS_VALUE           2434
#define IDC_EDIT_PORT                   2435
#define IDC_EDIT_POSID                  2436
#define IDC_EDIT_POSREFUND              2437
#define IDC_EDIT_POSSALEREFUND          2438
#define IDC_EDIT_POSTOPUP               2439
#define IDC_EDIT_PREVIOUSCARDNO         2440
#define IDC_EDIT_PRICELEVEL             2441
#define IDC_EDIT_PRINTER                2442
#define IDC_EDIT_PROMPT                 2443
#define IDC_EDIT_PURSE1                 2444
#define IDC_EDIT_PURSE1DATELASTUSED     2445
#define IDC_EDIT_PURSE1SPENDTD          2446
#define IDC_EDIT_PURSE1_BAL             2447
#define IDC_EDIT_PURSE1_CREDIT          2448
#define IDC_EDIT_PURSE1_DEPTSINHIBITED  2449
#define IDC_EDIT_PURSE1_LIABILITY       2450
#define IDC_EDIT_PURSE1_LOWBALANCE      2451
#define IDC_EDIT_PURSE1_MAXSPEND        2452
#define IDC_EDIT_PURSE1_OVERDRAFT       2453
#define IDC_EDIT_PURSE1_STD             2454
#define IDC_EDIT_PURSE1_TOTAL           2455
#define IDC_EDIT_PURSE1_USED_DATE       2456
#define IDC_EDIT_PURSE1_USED_TIME       2457
#define IDC_EDIT_PURSE1_USED_VALUE      2458
#define IDC_EDIT_PURSE2                 2459
#define IDC_EDIT_PURSE2DATELASTUSED     2460
#define IDC_EDIT_PURSE2SPENDTD          2461
#define IDC_EDIT_PURSE2_BALANCE         2462
#define IDC_EDIT_PURSE2_DEPTSINHIBITED  2463
#define IDC_EDIT_PURSE2_LOWBALANCE      2464
#define IDC_EDIT_PURSE2_REFRESH         2465
#define IDC_EDIT_PURSE2_REFRESHDAYS     2466
#define IDC_EDIT_PURSE2_REFRESH_DATE    2467
#define IDC_EDIT_PURSE2_REFRESH_TIME    2468
#define IDC_EDIT_PURSE2_REFRESH_VALUE   2469
#define IDC_EDIT_PURSE2_STD             2470
#define IDC_EDIT_PURSE2_USED_DATE       2471
#define IDC_EDIT_PURSE2_USED_TIME       2472
#define IDC_EDIT_PURSE2_USED_VALUE      2473
#define IDC_EDIT_PURSE3                 2474
#define IDC_EDIT_PURSE3DATELASTUSED     2475
#define IDC_EDIT_PURSE3SPENDTD          2476
#define IDC_EDIT_PURSE3_BAL             2477
#define IDC_EDIT_PURSE3_CREDIT          2478
#define IDC_EDIT_PURSE3_DEPTSINHIBITED  2479
#define IDC_EDIT_PURSE3_LIABILITY       2480
#define IDC_EDIT_PURSE3_LOWBALANCE      2481
#define IDC_EDIT_PURSE3_MAXSPEND        2482
#define IDC_EDIT_PURSE3_OVERDRAFT       2483
#define IDC_EDIT_PURSE3_STD             2484
#define IDC_EDIT_PURSE3_TOTAL           2485
#define IDC_EDIT_PURSE3_USED_DATE       2486
#define IDC_EDIT_PURSE3_USED_TIME       2487
#define IDC_EDIT_PURSE3_USED_VALUE      2488
#define IDC_EDIT_PWMASTER               2489
#define IDC_EDIT_REASON                 2490
#define IDC_EDIT_RECORDSADDED           2491
#define IDC_EDIT_RECORDSDELETED         2492
#define IDC_EDIT_RED                    2493
#define IDC_EDIT_REDDEMPOINTSTRIP       2494
#define IDC_EDIT_REDEEMVALUE            2495
#define IDC_EDIT_REFRESH1               2496
#define IDC_EDIT_REFRESH2               2497
#define IDC_EDIT_REFRESH3               2498
#define IDC_EDIT_REFRESH4               2499
#define IDC_EDIT_REFRESH5               2500
#define IDC_EDIT_REFRESH6               2501
#define IDC_EDIT_REPLYTO                2502
#define IDC_EDIT_REVALUEPOINTS          2503
#define IDC_EDIT_REVALUETRIP            2504
#define IDC_EDIT_REVALUETRIP2           2505
#define IDC_EDIT_REVALUEVALUE           2506
#define IDC_EDIT_REVALUE_POINTS         2507
#define IDC_EDIT_REVALUE_VALUE          2508
#define IDC_EDIT_REVERTGROUPNO          2509
#define IDC_EDIT_REWARDPOINTS           2510
#define IDC_EDIT_REWARDSPENDTRIP        2511
#define IDC_EDIT_REWARDTRIP             2512
#define IDC_EDIT_REWARDVALUE            2513
#define IDC_EDIT_SALENAME               2514
#define IDC_EDIT_SCHOOLID               2515
#define IDC_EDIT_SERVER                 2516
#define IDC_EDIT_SERVICEID              2517
#define IDC_EDIT_SERVICEID2             2518
#define IDC_EDIT_SETNO                  2519
#define IDC_EDIT_SHIFTGROUP             2520
#define IDC_EDIT_SIMSIMPORT             2521
#define IDC_EDIT_SMARTPAYUNCPATH1       2522
#define IDC_EDIT_SMARTPAYUNCPATH2       2523
#define IDC_EDIT_SNAPSHOTID             2524
#define IDC_EDIT_SNAPSHOTID2            2525
#define IDC_EDIT_SNAPSHOTID3            2526
#define IDC_EDIT_SPENDLIMIT             2527
#define IDC_EDIT_SPOS                   2528
#define IDC_EDIT_STAFFGROUPLIST         2529
#define IDC_EDIT_STAFFGROUPNO           2530
#define IDC_EDIT_STAMPS                 2531
#define IDC_EDIT_STARTOFWEEK10          2532
#define IDC_EDIT_STARTOFWEEK6           2533
#define IDC_EDIT_STARTOFWEEK9           2534
#define IDC_EDIT_SURNAME                2535
#define IDC_EDIT_TEXT                   2536
#define IDC_EDIT_TEXT1                  2537
#define IDC_EDIT_TEXT2                  2538
#define IDC_EDIT_TEXT3                  2539
#define IDC_EDIT_TEXT4                  2540
#define IDC_EDIT_THRESHOLD              2541
#define IDC_EDIT_TICK1                  2542
#define IDC_EDIT_TICK2                  2543
#define IDC_EDIT_TICK3                  2544
#define IDC_EDIT_TICK4                  2545
#define IDC_EDIT_TIME1                  2546
#define IDC_EDIT_TIME10                 2547
#define IDC_EDIT_TIME2                  2548
#define IDC_EDIT_TIME3                  2549
#define IDC_EDIT_TIME4                  2550
#define IDC_EDIT_TIME5                  2551
#define IDC_EDIT_TIME6                  2552
#define IDC_EDIT_TIME7                  2553
#define IDC_EDIT_TIME8                  2554
#define IDC_EDIT_TIME9                  2555
#define IDC_EDIT_TOCARDNO               2556
#define IDC_EDIT_TOP100                 2557
#define IDC_EDIT_TOTAL                  2558
#define IDC_EDIT_TRANSACTIONBLOCKSIZE   2559
#define IDC_EDIT_TRIP                   2560
#define IDC_EDIT_TRIP_PURSE1            2561
#define IDC_EDIT_TRIP_PURSE3            2562
#define IDC_EDIT_UNAPPLIED              2563
#define IDC_EDIT_UPGRADEPATH            2564
#define IDC_EDIT_UPPERSPENDLIMIT        2565
#define IDC_EDIT_USERNAME               2566
#define IDC_EDIT_VALUE1                 2567
#define IDC_EDIT_VALUE2                 2568
#define IDC_EDIT_VATA                   2569
#define IDC_EDIT_VATB                   2570
#define IDC_EDIT_VATC                   2571
#define IDC_EDIT_VATD                   2572
#define IDC_EDIT_VATE                   2573
#define IDC_EDIT_VATF                   2574
#define IDC_EDIT_VATG                   2575
#define IDC_EDIT_VATH                   2576
#define IDC_EDIT_VATI                   2577
#define IDC_EDIT_VATJ                   2578
#define IDC_EDIT_VATK                   2579
#define IDC_EDIT_VATL                   2580
#define IDC_EDIT_WEBREFUND              2581
#define IDC_EDIT_WEBTOPUP               2582
#define IDC_LIST                        2583
#define IDC_LIST1                       2584
#define IDC_LIST_ACTION                 2585
#define IDC_LIST_ARCHIVE                2586
#define IDC_LIST_CARDPICKER             2587
#define IDC_LIST_EXPORT                 2588
#define IDC_LIST_NEXT                   2589
#define IDC_LIST_PLU                    2590
#define IDC_LIST_RESULT                 2591
#define IDC_LIST_TRACE                  2592
#define IDC_LIST_VIEW1                  2593
#define IDC_LIST_VIEW2                  2594
#define IDC_LIST_VIEW3                  2595
#define IDC_PROGRESS1                   2596
#define IDC_RADIO2                      2597
#define IDC_RADIO3                      2598
#define IDC_RADIO_ALERT1                2599
#define IDC_RADIO_ALERT2                2600
#define IDC_RADIO_ALERT3                2601
#define IDC_RADIO_ALERT4                2602
#define IDC_RADIO_ALERT5                2603
#define IDC_RADIO_ALERT6                2604
#define IDC_RADIO_ALERT7                2605
#define IDC_RADIO_ALERT8                2606
#define IDC_RADIO_ALERT9                2607
#define IDC_RADIO_ALLGROUPS             2608
#define IDC_RADIO_CLEAR                 2609
#define IDC_RADIO_CUSTOM                2610
#define IDC_RADIO_DAILY                 2611
#define IDC_RADIO_DAY0                  2612
#define IDC_RADIO_DAY1                  2613
#define IDC_RADIO_DAY2                  2614
#define IDC_RADIO_DAY3                  2615
#define IDC_RADIO_DAY4                  2616
#define IDC_RADIO_DAY5                  2617
#define IDC_RADIO_DAY6                  2618
#define IDC_RADIO_DELETE1               2619
#define IDC_RADIO_DELETE2               2620
#define IDC_RADIO_DELETE3               2621
#define IDC_RADIO_EXISTING              2622
#define IDC_RADIO_GROUPNO               2623
#define IDC_RADIO_GROUPSETNO            2624
#define IDC_RADIO_HOURLY                2625
#define IDC_RADIO_IMPORTALL             2626
#define IDC_RADIO_LIST                  2627
#define IDC_RADIO_LISTGROUPS            2628
#define IDC_RADIO_METHOD1               2629
#define IDC_RADIO_METHOD2               2630
#define IDC_RADIO_METHOD3               2631
#define IDC_RADIO_MODE1                 2632
#define IDC_RADIO_MODE2                 2633
#define IDC_RADIO_MODE3                 2634
#define IDC_RADIO_MODE4                 2635
#define IDC_RADIO_NEW                   2636
#define IDC_RADIO_NONE                  2637
#define IDC_RADIO_PAYMENTALL            2638
#define IDC_RADIO_PAYMENTLIST           2639
#define IDC_RADIO_PHOTOID1              2640
#define IDC_RADIO_PHOTOID2              2641
#define IDC_RADIO_PHOTOID3              2642
#define IDC_RADIO_RANGE                 2643
#define IDC_RADIO_REGEN                 2644
#define IDC_RADIO_REPORTOUTPUT1         2645
#define IDC_RADIO_REPORTOUTPUT2         2646
#define IDC_RADIO_REPORTOUTPUT3         2647
#define IDC_RADIO_REVALUATIONPOINTS     2648
#define IDC_RADIO_REVALUATIONVALUE      2649
#define IDC_RADIO_REVALUE_POINTS        2650
#define IDC_RADIO_REVALUE_VALUE         2651
#define IDC_RADIO_REWARDPOINTS          2652
#define IDC_RADIO_REWARDVALUE           2653
#define IDC_RADIO_SINGLE                2654
#define IDC_RADIO_TICK1                 2655
#define IDC_RADIO_TICK2                 2656
#define IDC_RADIO_TICK3                 2657
#define IDC_RADIO_TICK4                 2658
#define IDC_RADIO_TICKNO1               2659
#define IDC_RADIO_TICKNO2               2660
#define IDC_RADIO_TICKNO3               2661
#define IDC_RADIO_TICKNO4               2662
#define IDC_RADIO_TICKYES1              2663
#define IDC_RADIO_TICKYES2              2664
#define IDC_RADIO_TICKYES3              2665
#define IDC_RADIO_TICKYES4              2666
#define IDC_RADIO_TYPE                  2667
#define IDC_RADIO_TYPE1                 2668
#define IDC_RADIO_TYPE2                 2669
#define IDC_RADIO_WEEKLY                2670
#define IDC_SLIDER_BLUE                 2671
#define IDC_SLIDER_GREEN                2672
#define IDC_SLIDER_RED                  2673
#define IDC_SPIN_CARDPICKER             2674
#define IDC_SPIN_DAYNO                  2675
#define IDC_SPIN_FIND                   2676
#define IDC_SPIN_GROUPSET               2677
#define IDC_SPIN_MULTIPLIER_FRI         2678
#define IDC_SPIN_MULTIPLIER_MON         2679
#define IDC_SPIN_MULTIPLIER_SAT         2680
#define IDC_SPIN_MULTIPLIER_SUN         2681
#define IDC_SPIN_MULTIPLIER_THU         2682
#define IDC_SPIN_MULTIPLIER_TUE         2683
#define IDC_SPIN_MULTIPLIER_WED         2684
#define IDC_SPIN_PRICELEVEL             2685
#define IDC_SPIN_REDEEMPOINTS           2686
#define IDC_STATIC0                     2687
#define IDC_STATIC1                     2688
#define IDC_STATIC2                     2689
#define IDC_STATIC3                     2690
#define IDC_STATIC4                     2691
#define IDC_STATIC5                     2692
#define IDC_STATIC_2NDBONUSTRIP         2693
#define IDC_STATIC_ACCESSTYPE           2694
#define IDC_STATIC_ACCOUNT1             2695
#define IDC_STATIC_ACCOUNT2             2696
#define IDC_STATIC_ACCOUNT3             2697
#define IDC_STATIC_ACCOUNT4             2698
#define IDC_STATIC_ACCOUNT5             2699
#define IDC_STATIC_ACCOUNTID            2700
#define IDC_STATIC_ACTION               2701
#define IDC_STATIC_ACTIVITY             2702
#define IDC_STATIC_AUDIT                2703
#define IDC_STATIC_AUDITOFF             2704
#define IDC_STATIC_AUTOSELECT           2705
#define IDC_STATIC_BIOREG               2706
#define IDC_STATIC_BIOREGISTER          2707
#define IDC_STATIC_BIOREGISTER1         2708
#define IDC_STATIC_BIOREGISTER2         2709
#define IDC_STATIC_BIOREGISTER3         2710
#define IDC_STATIC_BONUS                2711
#define IDC_STATIC_BONUSCOMMENT         2712
#define IDC_STATIC_CAPTION1             2713
#define IDC_STATIC_CAPTION2             2714
#define IDC_STATIC_CARDNOTEXT           2715
#define IDC_STATIC_COMMENT              2716
#define IDC_STATIC_COMMENTS             2717
#define IDC_STATIC_COMPRESSION          2718
#define IDC_STATIC_COUNT                2719
#define IDC_STATIC_DATE                 2720
#define IDC_STATIC_DATEFROM             2721
#define IDC_STATIC_DATETO               2722
#define IDC_STATIC_DEFAULT              2723
#define IDC_STATIC_DELPCTRL             2724
#define IDC_STATIC_DOT                  2725
#define IDC_STATIC_EODBOXTEXT           2726
#define IDC_STATIC_EPOS                 2727
#define IDC_STATIC_EXPORTBOX            2728
#define IDC_STATIC_EXPORTS1             2729
#define IDC_STATIC_EXPORTS2             2730
#define IDC_STATIC_EXPORTS3             2731
#define IDC_STATIC_EXPORTS4             2732
#define IDC_STATIC_EXPORTS5             2733
#define IDC_STATIC_EXPORTS6             2734
#define IDC_STATIC_EXTREF               2735
#define IDC_STATIC_EXTREF2              2736
#define IDC_STATIC_FIELDNAME            2737
#define IDC_STATIC_FILENAME             2738
#define IDC_STATIC_FOLDERSET            2739
#define IDC_STATIC_GENERAL_LABEL1       2740
#define IDC_STATIC_GENERAL_LABEL2       2741
#define IDC_STATIC_GENERAL_LABEL3       2742
#define IDC_STATIC_GROUPMAXSPEND        2743
#define IDC_STATIC_GROUPSHIFT           2744
#define IDC_STATIC_GROUPTEXT            2745
#define IDC_STATIC_IMPORT1              2746
#define IDC_STATIC_IMPORT2              2747
#define IDC_STATIC_IMPORT3              2748
#define IDC_STATIC_IMPORT4              2749
#define IDC_STATIC_IMPORT5              2750
#define IDC_STATIC_IMPORT6              2751
#define IDC_STATIC_IMPORT7              2752
#define IDC_STATIC_IMPORT8              2753
#define IDC_STATIC_IMPORT9              2754
#define IDC_STATIC_INCLUDE              2755
#define IDC_STATIC_INFO                 2756
#define IDC_STATIC_INFO1                2757
#define IDC_STATIC_INFO2                2758
#define IDC_STATIC_INFO3                2759
#define IDC_STATIC_INFO4                2760
#define IDC_STATIC_INFO5                2761
#define IDC_STATIC_INFO6                2762
#define IDC_STATIC_INFO7                2763
#define IDC_STATIC_INFO8                2764
#define IDC_STATIC_INFO_1A              2765
#define IDC_STATIC_INFO_1B              2766
#define IDC_STATIC_INSTALL              2767
#define IDC_STATIC_LABEL                2768
#define IDC_STATIC_LASTPAYMENTID        2770
#define IDC_STATIC_LASTPAYMENTID2       2771
#define IDC_STATIC_LINE1                2773
#define IDC_STATIC_LINE2                2774
#define IDC_STATIC_LINE3                2775
#define IDC_STATIC_LINE4                2776
#define IDC_STATIC_LINESIGNORED         2777
#define IDC_STATIC_LINESINVALID         2778
#define IDC_STATIC_LINESREAD            2779
#define IDC_STATIC_LINESUSED            2780
#define IDC_STATIC_LOCATEBY             2781
#define IDC_STATIC_LOGOFF1              2782
#define IDC_STATIC_LOGOFF2              2783
#define IDC_STATIC_LOOKINALL2           2784
#define IDC_STATIC_LOOKINALL3           2785
#define IDC_STATIC_MAXSPEND             2786
#define IDC_STATIC_MAXSPENDP1           2787
#define IDC_STATIC_MAXSPENDP3           2788
#define IDC_STATIC_MEMBERID             2789
#define IDC_STATIC_MESSAGE              2790
#define IDC_STATIC_MESSAGE1             2791
#define IDC_STATIC_MESSAGE2             2792
#define IDC_STATIC_MESSAGE3             2793
#define IDC_STATIC_MESSAGE4             2794
#define IDC_STATIC_MISC                 2795
#define IDC_STATIC_NEXT                 2796
#define IDC_STATIC_NEXTCARDNO           2797
#define IDC_STATIC_NEXTID               2798
#define IDC_STATIC_NOIMAGE              2799
#define IDC_STATIC_OPTIONS1             2800
#define IDC_STATIC_OPTIONS2             2801
#define IDC_STATIC_OPTIONS3             2802
#define IDC_STATIC_ORDERBY              2803
#define IDC_STATIC_ORDERBY2             2804
#define IDC_STATIC_OVERDRAFT            2805
#define IDC_STATIC_OVERDRAFTP3          2806
#define IDC_STATIC_OVERSPENDP1          2807
#define IDC_STATIC_OVERSPENDP3          2808
#define IDC_STATIC_PASSWORD             2809
#define IDC_STATIC_PAUSE                2810
#define IDC_STATIC_PAYMENT              2811
#define IDC_STATIC_PAYMENT1             2812
#define IDC_STATIC_PAYMENT2             2813
#define IDC_STATIC_PAYMENTS             2814
#define IDC_STATIC_PERIOD               2815
#define IDC_STATIC_PERIOD1              2816
#define IDC_STATIC_PERIOD2              2817
#define IDC_STATIC_PERIOD3              2818
#define IDC_STATIC_PERIOD4              2819
#define IDC_STATIC_PERIOD5              2820
#define IDC_STATIC_PERIOD6              2821
#define IDC_STATIC_PERIODTYPE1          2822
#define IDC_STATIC_PERIODTYPE2          2823
#define IDC_STATIC_PERIODTYPE3          2824
#define IDC_STATIC_PERIODTYPE4          2825
#define IDC_STATIC_PERIODTYPE5          2826
#define IDC_STATIC_PERIODTYPE6          2827
#define IDC_STATIC_PICTURE              2828
#define IDC_STATIC_PLUDATAPATH          2829
#define IDC_STATIC_POINTS               2830
#define IDC_STATIC_POINTS_LABEL1        2831
#define IDC_STATIC_POINTS_LABEL2        2832
#define IDC_STATIC_POINTS_LABEL3        2833
#define IDC_STATIC_POINTS_LABEL4        2834
#define IDC_STATIC_PORT                 2835
#define IDC_STATIC_POSID                2836
#define IDC_STATIC_PREVIOUSCARDNO       2837
#define IDC_STATIC_PROMPT               2838
#define IDC_STATIC_PROMPT2              2839
#define IDC_STATIC_PUPILSTARTFROM       2840
#define IDC_STATIC_PURCHASESTARTDATE    2841
#define IDC_STATIC_PURSE1               2842
#define IDC_STATIC_PURSE1TRIP           2843
#define IDC_STATIC_PURSE1_BALANCE       2844
#define IDC_STATIC_PURSE1_CREDIT        2845
#define IDC_STATIC_PURSE1_LIABILITY     2846
#define IDC_STATIC_PURSE1_MAXSPEND      2847
#define IDC_STATIC_PURSE1_OVERDRAFT     2848
#define IDC_STATIC_PURSE1_TOTAL         2849
#define IDC_STATIC_PURSE2               2850
#define IDC_STATIC_PURSE3               2851
#define IDC_STATIC_PURSE3TRIP           2852
#define IDC_STATIC_PURSE3_CREDIT        2853
#define IDC_STATIC_PURSE3_LABEL1        2854
#define IDC_STATIC_PURSE3_LABEL10       2855
#define IDC_STATIC_PURSE3_LABEL2        2856
#define IDC_STATIC_PURSE3_LABEL3        2857
#define IDC_STATIC_PURSE3_LABEL4        2858
#define IDC_STATIC_PURSE3_LABEL8        2859
#define IDC_STATIC_PURSE3_LABEL9        2860
#define IDC_STATIC_PURSE3_LIABILITY     2861
#define IDC_STATIC_PURSE3_MAXSPEND      2862
#define IDC_STATIC_PURSE3_OVERDRAFT     2863
#define IDC_STATIC_PURSE3_TOTAL         2864
#define IDC_STATIC_PURSEBONUS           2865
#define IDC_STATIC_PURSEREVALUE         2866
#define IDC_STATIC_PURSES               2867
#define IDC_STATIC_RECORDCOUNT          2868
#define IDC_STATIC_RECORDSADDED         2869
#define IDC_STATIC_RECORDSDELETED       2870
#define IDC_STATIC_REF                  2871
#define IDC_STATIC_REFRESH              2872
#define IDC_STATIC_REFRESHED1           2873
#define IDC_STATIC_REFRESHED2           2874
#define IDC_STATIC_REFRESHED3           2875
#define IDC_STATIC_REFRESHED4           2876
#define IDC_STATIC_REFRESHED5           2877
#define IDC_STATIC_REFRESHED6           2878
#define IDC_STATIC_REPORTBY             2879
#define IDC_STATIC_REPORTON             2880
#define IDC_STATIC_REPORTONBOXTEXT      2881
#define IDC_STATIC_RETAIN_PAYMENT       2882
#define IDC_STATIC_RETAIN_RECENT        2883
#define IDC_STATIC_RUN                  2884
#define IDC_STATIC_SCHEDULE1            2885
#define IDC_STATIC_SCHEDULE2            2886
#define IDC_STATIC_SERIALNO             2887
#define IDC_STATIC_SERVER               2888
#define IDC_STATIC_SETNO                2889
#define IDC_STATIC_SHIFTGROUP           2890
#define IDC_STATIC_SHOWBOX              2891
#define IDC_STATIC_SMARTPAYUNCPATH1     2892
#define IDC_STATIC_SMARTPAYUNCPATH2     2893
#define IDC_STATIC_SNAPSHOT             2894
#define IDC_STATIC_SNAPSHOT2            2895
#define IDC_STATIC_SNAPSHOT3            2896
#define IDC_STATIC_STAFFSTARTFROM       2897
#define IDC_STATIC_STAMPS               2898
#define IDC_STATIC_START                2899
#define IDC_STATIC_STARTPERIOD1         2900
#define IDC_STATIC_STARTPERIOD2         2901
#define IDC_STATIC_STARTPERIOD3         2902
#define IDC_STATIC_STARTPERIOD4         2903
#define IDC_STATIC_STARTPERIOD5         2904
#define IDC_STATIC_STARTPERIOD6         2905
#define IDC_STATIC_STATUS               2906
#define IDC_STATIC_SYSTEM               2907
#define IDC_STATIC_TICK1                2908
#define IDC_STATIC_TICK2                2909
#define IDC_STATIC_TICK3                2910
#define IDC_STATIC_TICK4                2911
#define IDC_STATIC_TICKBOX              2912
#define IDC_STATIC_TIME                 2913
#define IDC_STATIC_TIMEEND              2914
#define IDC_STATIC_TIMESTART            2915
#define IDC_STATIC_TO                   2916
#define IDC_STATIC_TO1                  2917
#define IDC_STATIC_TO2                  2918
#define IDC_STATIC_TOP100               2919
#define IDC_STATIC_TOPUPTYPE            2920
#define IDC_STATIC_TYPE                 2921
#define IDC_STATIC_UIDTYPE              2922
#define IDC_STATIC_USER                 2923
#define IDC_STATIC_USERNAME             2924
#define IDC_STATIC_USERTYPE1            2925
#define IDC_STATIC_USERTYPE2            2926
#define IDC_STATIC_USERTYPES            2927
#define IDC_STATIC_VATA                 2928
#define IDC_STATIC_VATB                 2929
#define IDC_STATIC_VATC                 2930
#define IDC_STATIC_VATD                 2931
#define IDC_STATIC_VATE                 2932
#define IDC_STATIC_VATF                 2933
#define IDC_STATIC_VATG                 2934
#define IDC_STATIC_VATH                 2935
#define IDC_STATIC_VATI                 2936
#define IDC_STATIC_VATJ                 2937
#define IDC_STATIC_VATK                 2938
#define IDC_STATIC_VATL                 2939
#define IDC_STATIC_VATNOTE1             2940
#define IDC_STATIC_VATNOTE2             2941
#define IDC_STATIC_VATNOTE3             2942
#define IDC_STATIC_VATNOTE4             2943
#define IDC_STATIC_VATNOTE5             2944
#define IDC_STATIC_VATNOTE6             2945
#define IDC_STATIC_VERSION              2946
#define IDC_STATIC_WARNING              2947
#define IDC_STATIC_WEBPAYMENT_MESSAGE   2948
#define IDC_TAB_ACTIONS                 2949
#define IDC_TAB_EPOS                    2950
#define IDC_TAB_FOLDERS                 2951
#define IDC_TAB_SEARCH                  2952
#define IDC_TAB_STATUS                  2953
#define IDC_TIMEPICKER_DAILY            2954
#define IDC_TIMEPICKER_FROM             2955
#define IDC_TIMEPICKER_FROM_SALE        2956
#define IDC_TIMEPICKER_FROM_TOPUP       2957
#define IDC_TIMEPICKER_TO               2958
#define IDC_TIMEPICKER_WEEKLY           2959
#define IDI_ICON_BACKGROUND             2960
#define IDI_ICON_SMARTPAYSERVER         2961
#define IDS_ABOUTBOX                    2962
#define WM_AUTOBACKUP                   2964
#define IDC_EDIT_REFRESH                2965
#define IDC_CHECK_PURSE1ONLY            2966
#define IDC_CHECK1                      2966
#define IDC_CHECK_EXCLUDE               2966
#define IDC_CHECK_KEEP                  2966
#define IDC_CHECK_ZEROSKIPVAT           2967
#define IDC_CHECK2                      2967
#define IDC_CHECK_REMOVE                2967
#define IDC_EDIT_ADD_FROM               2967
#define IDC_CHECK_LOOKUP_PIN            2968
#define IDC_EDIT_ADD_TO                 2968
#define IDC_COMBO_ADD_GROUP             2969
#define IDC_EDIT_REMOVE_FROM            2970
#define IDC_EDIT_REMOVE_TO              2971
#define IDC_COMBO_REMOVE_GROUP          2972
#define IDC_BUTTON_ALTKEY4              2973
#define IDM_AUDIT_ARCHIVE               32771
#define IDM_AUDIT_CREDIT                32772
#define IDM_AUDIT_EPOSPAYMENTS          32773
#define IDM_AUDIT_KIOSKTOPUPS           32774
#define IDM_AUDIT_POINTSADDED           32775
#define IDM_AUDIT_POINTSAUDIT           32776
#define IDM_AUDIT_POINTSDEDUCTED        32777
#define IDM_AUDIT_PURSEADDITIONS        32778
#define IDM_AUDIT_REDEEMBONUS           32779
#define IDM_AUDIT_REFUNDS               32780
#define IDM_AUDIT_SALES                 32781
#define IDM_BACKGROUND_ABOUT            32782
#define IDM_BACKGROUND_CLOSE            32783
#define IDM_BACKGROUND_LICENCEDETAILS   32784
#define IDM_BACKGROUND_TIMETABLE        32785
#define IDM_BACKUP_LOG                  32786
#define IDM_BACKUP_STATUS               32787
#define IDM_BACKUP_SYSTEM               32788
#define IDM_BATCH_ADDCARDS              32789
#define IDM_BATCH_DELETE                32790
#define IDM_BATCH_REDEEM                32791
#define IDM_BATCH_UPDATE                32792
#define IDM_CARDUSAGE_ACTIVECARDS       32793
#define IDM_CARDUSAGE_INACTIVECARDS     32794
#define IDM_CARDUSAGE_LOWPOINTS         32795
#define IDM_CARDUSAGE_LOWSPEND          32796
#define IDM_CARDUSAGE_NEVERUSED         32797
#define IDM_CARDUSAGE_RANKINGPOINTS     32798
#define IDM_CARDUSAGE_RANKINGPURCHASES  32799
#define IDM_CARDUSAGE_RANKINGSPEND      32800
#define IDM_COLUMN_DEFAULT              32801
#define IDM_COLUMN_EDIT                 32802
#define IDM_COLUMN_RESTORE              32803
#define IDM_COLUMN_SAVE                 32804
#define IDM_EDIT_CLEARALL               32805
#define IDM_EDIT_INVERTSELECTION        32806
#define IDM_EDIT_PREVIOUS               32807
#define IDM_EDIT_SELECTALL              32808
#define IDM_EMAIL_LOG                   32809
#define IDM_EMAIL_LOWBALANCE            32810
#define IDM_EMAIL_POINTSACHIEVEMENT     32811
#define IDM_EMAIL_PURCHASES             32812
#define IDM_EMAIL_WEEKLYPOINTS          32813
#define IDM_EXPORT_SALESTOPUPS          32814
#define IDM_FILE_ARCHIVE                32815
#define IDM_FILE_BGND_SERVICE           32816
#define IDM_FILE_BGND_SERVICELOG        32817
#define IDM_FILE_EXIT                   32818
#define IDM_FILE_EXITCARDPICKER         32819
#define IDM_FILE_EXPORT                 32820
#define IDM_FILE_IMPORT                 32821
#define IDM_FILE_REFRESH                32822
#define IDM_FILE_SERVER_SERVICE         32823
#define IDM_FILE_SERVER_SERVICELOG      32824
#define IDM_FILE_SIGNOFF                32825
#define IDM_FILE_TERMINALLIST           32826
#define IDM_FILE_TIMETABLE              32827
#define IDM_FILE_UPGRADE                32828
#define IDM_FILE_WEBPAYMENTBALANCES     32829
#define IDM_FILE_WEBPAYMENTENDOFDAY     32830
#define IDM_FILE_WEBPAYMENTIMPORT       32831
#define IDM_FILE_WEBPAYMENTLINKACCOUNTS 32832
#define IDM_FILE_WEBPAYMENTLOG          32833
#define IDM_FROMFILE_VIAMEMBERID        32834
#define IDM_FROMFILE_VIAUSERID          32835
#define IDM_HELP_LICENCEDETAILS         32836
#define IDM_HELP_SMARTPAYMANAGER        32837
#define IDM_IMPORT_AUDITDATA            32838
#define IDM_IMPORT_AUTOFILE             32839
#define IDM_IMPORT_CUSTOMFILE           32840
#define IDM_IMPORT_LEAVERS              32841
#define IDM_IMPORT_SIMSFILE             32842
#define IDM_IMPORT_TOPUPFILE            32843
#define IDM_IMPORT_WONDEFILE            32844
#define IDM_PEBBLE_BALANCES             32845
#define IDM_PEBBLE_LINKTIMES            32846
#define IDM_POPUP_ADD                   32847
#define IDM_POPUP_ALERT                 32848
#define IDM_POPUP_AUDIT                 32849
#define IDM_POPUP_AUDIT_SUMMARY         32850
#define IDM_POPUP_CREDIT                32851
#define IDM_POPUP_DELETE                32852
#define IDM_POPUP_EDIT                  32853
#define IDM_POPUP_GROUPSHIFT            32854
#define IDM_POPUP_HOTLIST               32855
#define IDM_POPUP_HOTLISTREPLACE        32856
#define IDM_POPUP_MEAL                  32857
#define IDM_POPUP_PEBBLELINK            32858
#define IDM_POPUP_PHOTOID               32859
#define IDM_POPUP_PURCHASECONTROLS      32860
#define IDM_POPUP_PURCHASEHISTORY       32861
#define IDM_POPUP_REPLACE               32862
#define IDM_POPUP_STATEMENT             32863
#define IDM_POPUP_TOPUP                 32864
#define IDM_POPUP_TOPUP2                32865
#define IDM_POPUP_TOPUP3                32866
#define IDM_POPUP_TRACE                 32867
#define IDM_POPUP_TRANSFER              32868
#define IDM_POPUP_UNHOTLIST             32869
#define IDM_PURCHASES_BREAKDOWN         32870
#define IDM_PURCHASES_STATEMENTS        32871
#define IDM_REPORTS_AUDIT               32872
#define IDM_REPORTS_AUDIT_SUMMARY       32873
#define IDM_REPORTS_BIRTHDAYS           32874
#define IDM_REPORTS_CASHTAKEN           32875
#define IDM_REPORTS_DATABASE            32876
#define IDM_REPORTS_ENDOFDAY            32877
#define IDM_REPORTS_GROUPPERIODSALES    32878
#define IDM_REPORTS_GROUPSHIFTLOG       32879
#define IDM_REPORTS_LEAVERS             32880
#define IDM_REPORTS_PHOTOIDLIST         32881
#define IDM_REPORTS_PURCHASECONTROLS    32882
#define IDM_REPORTS_PURCHASEHISTORY     32883
#define IDM_REPORTS_REVALUEBONUS        32884
#define IDM_REPORTS_SPENDBONUS          32885
#define IDM_REPORTS_STARTINGBALANCE     32886
#define IDM_RESTORE_EXISTING            32888
#define IDM_RESTORE_SCRIPT              32889
#define IDM_RESTORE_SEPARATE            32890
#define IDM_SETUP_GROUPS                32891
#define IDM_SETUP_PURCHASECONTROL       32892
#define IDM_SETUP_SERVER                32893
#define IDM_SETUP_SYSTEM                32894
#define IDM_USAGE_WEEKLYSPEND           32895

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32896
#define _APS_NEXT_CONTROL_VALUE         2970
#define _APS_NEXT_SYMED_VALUE           1048
#endif
#endif
