//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CardLink.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_PROGRESS                 101
#define IDD_EMPTYCASH                   102
#define IDD_ERRORDLG                    103
#define IDD_GETADMINDLG                 104
#define IDD_GETDUALDLG                  105
#define IDD_GETUSER2DLG                 106
#define IDD_GETUSERDLG                  107
#define IDD_KEYPADDLG                   108
#define IDD_LOADERTEST                  109
#define IDD_PHOTOENQUIRYDLG             110
#define IDD_SCANNERDLG                  111
#define IDD_SELECTIONDLG                112
#define IDD_SELECTPURSEDLG              113
#define IDD_SERVICETIMESDLG             114
#define IDD_SETUPDLG                    115
#define IDD_SETUPREADERDLG              116
#define IDD_WAITDLG                     117
#define IDD_YESNOCANCELDLG              118
#define IDD_YESNODLG                    118
#define IDR_MAINFRAME                   119
#define IDD_SCANNERDLG1                 119
#define IDD_WAITSTATUS                  120
#define IDC_BUTTON_0                    1500
#define IDC_BUTTON_1                    1501
#define IDC_BUTTON_2                    1502
#define IDC_BUTTON_3                    1503
#define IDC_BUTTON_4                    1504
#define IDC_BUTTON_5                    1505
#define IDC_BUTTON_6                    1506
#define IDC_BUTTON_7                    1507
#define IDC_BUTTON_8                    1508
#define IDC_BUTTON_9                    1509
#define IDC_BUTTON_BIOMETRIC            1510
#define IDC_BUTTON_BROWSE1              1511
#define IDC_BUTTON_BROWSE2              1512
#define IDC_BUTTON_BROWSE3              1513
#define IDC_BUTTON_CANCEL               1514
#define IDC_BUTTON_CHECKBIOMETRIC       1515
#define IDC_BUTTON_CLEAR                1516
#define IDC_BUTTON_EMPTYCASH            1517
#define IDC_BUTTON_IMAGE1               1518
#define IDC_BUTTON_IMAGE2               1519
#define IDC_BUTTON_LICENCE              1520
#define IDC_BUTTON_MANUAL               1521
#define IDC_BUTTON_NEXT                 1522
#define IDC_BUTTON_NO                   1523
#define IDC_BUTTON_PREVIOUS             1524
#define IDC_BUTTON_READCARD             1525
#define IDC_BUTTON_REFRESH              1526
#define IDC_BUTTON_REPORT1              1527
#define IDC_BUTTON_REPORT2              1528
#define IDC_BUTTON_REPORT3              1529
#define IDC_BUTTON_SERVICE              1530
#define IDC_BUTTON_SETUP                1531
#define IDC_BUTTON_TERMINAL             1532
#define IDC_BUTTON_TERMINATE            1533
#define IDC_BUTTON_TEST                 1534
#define IDC_BUTTON_TEST1                1535
#define IDC_BUTTON_TEST2                1536
#define IDC_BUTTON_TEST3                1537
#define IDC_BUTTON_TOPUP                1538
#define IDC_BUTTON_TOPUP2               1539
#define IDC_BUTTON_YES                  1540
#define IDC_CHECK_BALANCEONLY1          1541
#define IDC_CHECK_BALANCEONLY2          1542
#define IDC_CHECK_BALANCEONLY3          1543
#define IDC_CHECK_BALANCEONLY4          1544
#define IDC_CHECK_BALANCEONLY5          1545
#define IDC_CHECK_DISABLEALERTS         1546
#define IDC_CHECK_ENROLMENT             1547
#define IDC_CHECK_HIDEACCOUNTID         1548
#define IDC_CHECK_KEYPADENTRY           1549
#define IDC_CHECK_PASSWORDREQD          1550
#define IDC_CHECK_PURSE1TOPUP           1551
#define IDC_CHECK_PURSE3TOPUP           1552
#define IDC_CHECK_SHOWAVAILABLESPEND    1553
#define IDC_CHECK_SHOWDATETIME          1554
#define IDC_CHECK_SHOWGROUP             1555
#define IDC_CHECK_SHOWPHOTOID           1556
#define IDC_CHECK_SHOWPOINTS            1557
#define IDC_COMBO_BAUD                  1558
#define IDC_CHECK_NOSMALLCOINWARN       1558
#define IDC_COMBO_DATAFORMAT            1559
#define IDC_CHECK_NOSMALLCOINWARN2      1559
#define IDC_CHECK_SHOWUSERIDCANCEL      1559
#define IDC_COMBO_FORMAT                1560
#define IDC_COMBO_INTERFACE             1561
#define IDC_COMBO_LIBS                  1562
#define IDC_COMBO_INTERFACE2            1562
#define IDC_COMBO_PINPAD                1562
#define IDC_COMBO_LOCATEON              1563
#define IDC_COMBO_PORT                  1564
#define IDC_COMBO_READER                1565
#define IDC_DATETIMEPICKER1             1566
#define IDC_DATETIMEPICKER10            1567
#define IDC_DATETIMEPICKER2             1568
#define IDC_DATETIMEPICKER3             1569
#define IDC_DATETIMEPICKER4             1570
#define IDC_DATETIMEPICKER5             1571
#define IDC_DATETIMEPICKER6             1572
#define IDC_DATETIMEPICKER7             1573
#define IDC_DATETIMEPICKER8             1574
#define IDC_DATETIMEPICKER9             1575
#define IDC_EDIT_CARDNOTEXT             1576
#define IDC_EDIT_CCNO                   1577
#define IDC_EDIT_CID                    1578
#define IDC_EDIT_ENROLPROMPT            1579
#define IDC_EDIT_GT                     1580
#define IDC_EDIT_IMPORTFILE             1581
#define IDC_EDIT_KBINPUT                1582
#define IDC_EDIT_LOYLOGFOLDER           1583
#define IDC_EDIT_LOYREQFOLDER           1584
#define IDC_EDIT_NOTIFYPATH             1585
#define IDC_EDIT_PASSWORD               1586
#define IDC_EDIT_PURSE1TEXT             1587
#define IDC_EDIT_PURSE3TEXT             1588
#define IDC_EDIT_REFRESHINTERVAL        1589
#define IDC_EDIT_SERIALNO               1590
#define IDC_EDIT_TERMINALNO             1591
#define IDC_EDIT_TIMEOUT                1592
#define IDC_ENABLESERVICE1              1593
#define IDC_ENABLESERVICE2              1594
#define IDC_ENABLESERVICE3              1595
#define IDC_ENABLESERVICE4              1596
#define IDC_ENABLESERVICE5              1597
#define IDC_STATIC_10                   1598
#define IDC_STATIC_100                  1599
#define IDC_STATIC_1000                 1600
#define IDC_STATIC_20                   1601
#define IDC_STATIC_200                  1602
#define IDC_STATIC_2000                 1603
#define IDC_STATIC_50                   1604
#define IDC_STATIC_500                  1605
#define IDC_STATIC_AVAILABLESPEND       1606
#define IDC_STATIC_BALANCE              1607
#define IDC_STATIC_CARDNO1              1608
#define IDC_STATIC_CARDNO2              1609
#define IDC_STATIC_CASHADDED            1610
#define IDC_STATIC_CCNO                 1611
#define IDC_STATIC_COPYRIGHT            1612
#define IDC_STATIC_COUNT1               1613
#define IDC_STATIC_COUNT2               1614
#define IDC_STATIC_DATETIME             1615
#define IDC_STATIC_DISPLAY              1616
#define IDC_STATIC_FORENAME1            1617
#define IDC_STATIC_FORENAME2            1618
#define IDC_STATIC_GROUPNO              1619
#define IDC_STATIC_GROUPNO1             1620
#define IDC_STATIC_GROUPNO2             1621
#define IDC_STATIC_GT                   1622
#define IDC_STATIC_IMPORTFILE           1623
#define IDC_STATIC_LASTUSED             1624
#define IDC_STATIC_NOIMAGE              1625
#define IDC_STATIC_NOTACCEPTED          1626
#define IDC_STATIC_PICTURE              1627
#define IDC_STATIC_POINTS               1628
#define IDC_STATIC_PROMPT               1629
#define IDC_STATIC_PROMPT2              1630
#define IDC_STATIC_QTY10                1631
#define IDC_STATIC_QTY100               1632
#define IDC_STATIC_QTY1000              1633
#define IDC_STATIC_QTY20                1634
#define IDC_STATIC_QTY200               1635
#define IDC_STATIC_QTY2000              1636
#define IDC_STATIC_QTY50                1637
#define IDC_STATIC_QTY500               1638
#define IDC_STATIC_SERIALNO             1639
#define IDC_STATIC_SURNAME              1640
#define IDC_STATIC_SURNAME1             1641
#define IDC_STATIC_SURNAME2             1642
#define IDC_STATIC_TEXT10               1643
#define IDC_STATIC_TEXT100              1644
#define IDC_STATIC_TEXT1000             1645
#define IDC_STATIC_TEXT20               1646
#define IDC_STATIC_TEXT200              1647
#define IDC_STATIC_TEXT2000             1648
#define IDC_STATIC_TEXT50               1649
#define IDC_STATIC_TEXT500              1650
#define IDC_STATIC_TEXTADDED            1651
#define IDC_STATIC_TEXTAVAILABLESPEND   1652
#define IDC_STATIC_TEXTBALANCE          1653
#define IDC_STATIC_TEXTCARDNO           1654
#define IDC_STATIC_TEXTGROUPNO          1655
#define IDC_STATIC_TEXTGROUPNO1         1656
#define IDC_STATIC_TEXTGROUPNO2         1657
#define IDC_STATIC_TEXTLASTUSED         1658
#define IDC_STATIC_TEXTPOINTS           1659
#define IDC_STATIC_TITLE                1660
#define IDC_STATIC_TOTALTEXT            1661
#define IDC_STATIC_TOTALVALUE           1662
#define IDC_STATIC_VERSION              1663
#define IDP_SOCKETS_INIT_FAILED         1664

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1665
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
