//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CardLink.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_PHOTOENQUIRYDLG             129
#define IDD_ERRORDLG                    148
#define IDD_WAITDLG                     153
#define IDD_GETUSERDLG                  154
#define IDD_SETUPDLG                    155
#define IDD_SELECTIONDLG                156
#define IDD_KEYPADDLG                   157
#define IDD_GETADMINDLG                 158
#define IDD_SERVICETIMESDLG             159
#define IDD_YESNOCANCELDLG              160
#define IDD_GETUSER2DLG                 161
#define IDD_LOADERTEST                  162
#define IDD_EMPTYCASH                   163
#define IDD_SETUPREADERDLG              164
#define IDD_SCANNERDLG                  167
#define IDD_GETDUALDLG                  168
#define IDD_SELECTPURSEDLG              169
#define IDC_STATIC_PROMPT               1000
#define IDC_STATIC_VERSION              1001
#define IDC_STATIC_PROMPT2              1001
#define IDC_COMBO_LIBS                  1002
#define IDC_STATIC_PICTURE              1014
#define IDC_BUTTON_BROWSE2              1032
#define IDC_BUTTON_SETUP                1033
#define IDC_BUTTON_BROWSE3              1033
#define IDC_BUTTON_LICENCE              1034
#define IDC_BUTTON_REFRESH              1035
#define IDC_EDIT_PASSWORD               1047
#define IDC_EDIT_TERMINALNO             1062
#define IDC_EDIT_CCNO                   1065
#define IDC_STATIC_TITLE                1088
#define IDC_STATIC_SERIALNO             1103
#define IDC_STATIC_CCNO                 1109
#define IDC_CHECK_PASSWORDREQD          1110
#define IDC_BUTTON_TOPUP                1116
#define IDC_BUTTON_EMPTYCASH            1117
#define IDC_STATIC_TEXTPOINTS           1123
#define IDC_STATIC_SURNAME              1131
#define IDC_STATIC_GROUPNO              1133
#define IDC_STATIC_BALANCE              1135
#define IDC_STATIC_POINTS               1136
#define IDC_STATIC_LASTUSED             1137
#define IDC_STATIC_CASHADDED            1139
#define IDC_STATIC_TEXTBALANCE          1141
#define IDC_STATIC_TEXTGROUPNO          1142
#define IDC_EDIT_LOYREQFOLDER           1151
#define IDC_EDIT_LOYLOGFOLDER           1152
#define IDC_BUTTON_BROWSE1              1153
#define IDC_EDIT_NOTIFYPATH             1154
#define IDC_BUTTON_IMAGE1               1156
#define IDC_BUTTON_IMAGE2               1157
#define IDC_STATIC_CARDNO1              1160
#define IDC_STATIC_SURNAME1             1161
#define IDC_STATIC_SURNAME2             1162
#define IDC_STATIC_CARDNO2              1163
#define IDC_STATIC_FORENAME1            1168
#define IDC_STATIC_TEXTGROUPNO1         1169
#define IDC_STATIC_GROUPNO1             1170
#define IDC_STATIC_GROUPNO2             1171
#define IDC_STATIC_TEXTGROUPNO2         1172
#define IDC_STATIC_FORENAME2            1173
#define IDC_BUTTON_NEXT                 1180
#define IDC_BUTTON_PREVIOUS             1181
#define IDC_STATIC_COUNT1               1183
#define IDC_STATIC_COUNT2               1184
#define IDC_STATIC_NOIMAGE              1184
#define IDC_STATIC_TEXTADDED            1186
#define IDC_BUTTON_TERMINATE            1187
#define IDC_BUTTON_1                    1189
#define IDC_BUTTON_2                    1190
#define IDC_BUTTON_3                    1191
#define IDC_BUTTON_4                    1192
#define IDC_BUTTON_5                    1193
#define IDC_BUTTON_6                    1194
#define IDC_BUTTON_7                    1195
#define IDC_BUTTON_8                    1196
#define IDC_BUTTON_9                    1197
#define IDC_BUTTON_0                    1198
#define IDC_BUTTON_CLEAR                1199
#define IDC_BUTTON_NO                   1199
#define IDC_BUTTON_REPORT1              1199
#define IDC_BUTTON_TEST1                1199
#define IDC_STATIC_DISPLAY              1200
#define IDC_BUTTON_REPORT2              1200
#define IDC_BUTTON_TEST2                1200
#define IDC_BUTTON_SERVICE              1201
#define IDC_BUTTON_REPORT3              1201
#define IDC_BUTTON_TEST3                1202
#define IDC_ENABLESERVICE1              1203
#define IDC_ENABLESERVICE2              1204
#define IDC_ENABLESERVICE3              1205
#define IDC_ENABLESERVICE4              1206
#define IDC_ENABLESERVICE5              1207
#define IDC_DATETIMEPICKER1             1209
#define IDC_DATETIMEPICKER2             1210
#define IDC_DATETIMEPICKER3             1211
#define IDC_DATETIMEPICKER4             1212
#define IDC_DATETIMEPICKER5             1213
#define IDC_DATETIMEPICKER6             1214
#define IDC_DATETIMEPICKER7             1215
#define IDC_DATETIMEPICKER8             1216
#define IDC_DATETIMEPICKER9             1217
#define IDC_DATETIMEPICKER10            1218
#define IDC_STATIC_TEXTLASTUSED         1221
#define IDC_CHECK_BALANCEONLY1          1222
#define IDC_CHECK_BALANCEONLY2          1223
#define IDC_BUTTON_YES                  1223
#define IDC_CHECK_BALANCEONLY3          1224
#define IDC_EDIT_IMPORTFILE             1224
#define IDC_CHECK_BALANCEONLY4          1225
#define IDC_BUTTON_CHECKBIOMETRIC       1225
#define IDC_CHECK_BALANCEONLY5          1226
#define IDC_STATIC_IMPORTFILE           1226
#define IDC_EDIT_CID                    1227
#define IDC_EDIT_GT                     1228
#define IDC_STATIC_GT                   1229
#define IDC_CHECK_SHOWPOINTS            1230
#define IDC_CHECK_SHOWGROUP             1231
#define IDC_EDIT_REFRESHINTERVAL        1232
#define IDC_EDIT_TIMEOUT                1233
#define IDC_BUTTON_MANUAL               1237
#define IDC_BUTTON_TEST                 1237
#define IDC_BUTTON_TERMINAL             1237
#define IDC_CHECK_SHOWPHOTOID           1238
#define IDC_EDIT_SERIALNO               1239
#define IDC_EDIT_KBINPUT                1239
#define IDC_CHECK_KEYPADENTRY           1240
#define IDC_COMBO_INTERFACE             1241
#define IDC_STATIC_2000                 1243
#define IDC_STATIC_TEXT2000             1244
#define IDC_STATIC_1000                 1245
#define IDC_STATIC_NOTACCEPTED          1245
#define IDC_STATIC_TEXT1000             1246
#define IDC_STATIC_TEXTCARDNO           1246
#define IDC_STATIC_500                  1247
#define IDC_STATIC_TEXTAVAILABLESPEND   1247
#define IDC_STATIC_TEXT500              1248
#define IDC_STATIC_200                  1249
#define IDC_STATIC_AVAILABLESPEND       1249
#define IDC_STATIC_TEXT200              1250
#define IDC_STATIC_COPYRIGHT            1250
#define IDC_STATIC_100                  1251
#define IDC_COMBO_PORT                  1251
#define IDC_COMBO_BAUD                  1252
#define IDC_COMBO_READER                1253
#define IDC_STATIC_TEXT100              1254
#define IDC_COMBO_FORMAT                1254
#define IDC_STATIC_50                   1255
#define IDC_STATIC_TEXT50               1256
#define IDC_STATIC_20                   1257
#define IDC_STATIC_TEXT20               1258
#define IDC_STATIC_10                   1259
#define IDC_STATIC_TEXT10               1260
#define IDC_STATIC_QTY2000              1261
#define IDC_STATIC_QTY1000              1262
#define IDC_STATIC_QTY500               1263
#define IDC_STATIC_QTY200               1264
#define IDC_STATIC_QTY100               1265
#define IDC_STATIC_QTY50                1266
#define IDC_STATIC_QTY20                1267
#define IDC_STATIC_QTY10                1268
#define IDC_STATIC_TOTALVALUE           1269
#define IDC_STATIC_TOTALTEXT            1270
#define IDC_CHECK_HIDEACCOUNTID         1271
#define IDC_CHECK_ENROLMENT             1272
#define IDC_EDIT_ENROLPROMPT            1273
#define IDC_EDIT_CARDNOTEXT             1274
#define IDC_CHECK_SHOWAVAILABLESPEND    1275
#define IDC_BUTTON_READCARD             1276
#define IDC_BUTTON_BIOMETRIC            1277
#define IDC_BUTTON_CANCEL               1277
#define IDC_CHECK_DISABLEALERTS         1278
#define IDC_COMBO_DATAFORMAT            1280
#define IDC_COMBO_LOCATEON              1282
#define IDC_STATIC_DATETIME             1284
#define IDC_CHECK_SHOWDATETIME          1285
#define IDC_BUTTON_TOPUP2               1286
#define IDC_CHECK_PURSE1TOPUP           1287
#define IDC_CHECK_PURSE3TOPUP           1288
#define IDC_EDIT_PURSE1TEXT             1289
#define IDC_EDIT_PURSE3TEXT             1290

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1291
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
