//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sysset3.rc
//
#define IDD_SYSSET_DLG1                 800
#define IDD_SYSSET_DLG2                 801
#define IDD_SYSSET_DLG3                 802
#define IDD_SYSSET_DLG4                 803
#define IDC_SYSSET_STATIC_COMMENT1      1001
#define IDC_SYSSET_STATIC_COMMENT2      1002
#define IDC_SYSSET_STATIC_RANDOM        1003
#define IDC_SYSSET_DATETIMEPICKER1      1004
#define IDC_SYSSET_STATIC_GROUP1        1005
#define IDC_SYSSET_STATIC_GROUP2        1006
#define IDC_SYSSET_STATIC_GROUP3        1007
#define IDC_SYSSET_STATIC_LINE1         1008
#define IDC_SYSSET_STATIC_LINE2         1009
#define IDC_SYSSET_STATIC_LINE3         1010
#define IDC_SYSSET_STATIC_LINE4         1011
#define IDC_SYSSET_STATIC_LINE5         1012
#define IDC_SYSSET_STATIC_LINE6         1013
#define IDC_SYSSET_EDIT_USERPASSWORD    1014
#define IDC_SYSSET_STATIC_USERADD1      1015
#define IDC_SYSSET_STATIC_USERADD2      1016
#define IDC_SYSSET_STATIC_USERADD3      1017
#define IDC_SYSSET_STATIC_USERADD4      1018
#define IDC_SYSSET_STATIC_USERADD5      1019
#define IDC_SYSSET_STATIC_USERNAME      1020
#define IDC_SYSSET_BUTTON_CLEAR_EXPIRY  1021
#define IDC_SYSSET_STATIC_TEXT          1022
#define IDC_BUTTON_SECRET		        1023
#define IDC_SYSSET_EDIT_DEALER_PHONE    1024
#define IDC_SYSSET_STATIC_PHONE         1025
#define IDC_SYSSET_STATIC_EXPIRY        1026
#define IDC_SYSSET_BUTTON_REGISTER_ONLINE 1027
#define IDC_SYSSET_STATIC_WAIT_MESSAGE  1028
#define IDC_SYSSET_LIST_USERS           1029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        804
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           804
#endif
#endif
